From :  $7500 Credit Limit <mbulacu@netaccessproviders.net>
Sent :  Thursday, November 27, 2003 6:53 PM
To :  mbulacu@hotmail.com
Subject :  Unsecured Platinum Card (7500-limit-/easy-qualify)


mbulacu, 02:53:16 PM, 11/27/2003

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<

You don't have to settle for less

http://140.186.141.225/two/upcc/upcc.htm

We have some great news. You have been selected for a 
(7500 limit) unsecured credit card. Even if you've had
past credit-problems or no credit-history. So you don't 
have to worry about having been turned down before.

Getyour card today

http://140.186.141.225/two/upcc/upcc.htm

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<


Modify your list settings
http://140.186.141.225/two/upcc/updates.htm


>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<


_________________________________________________________________
I keep forgetting to close the window
http://140.186.141.225/two/upcc/other.htm

volume:18383D1E42560D06070019303A100A0025231D...
