From n86qkr@yahoo.com Sun Nov 16 18:28:07 2003
Return-Path: <n86qkr@yahoo.com>
Received: from dep.ppsw.rug.nl (dep.ppsw.rug.nl [129.125.153.250])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAGHVPOj007723
	for <m.bulacu@tcw2.ai.rug.nl>; Sun, 16 Nov 2003 18:31:25 +0100
Received: from 200-153-199-86.dsl.telesp.net.br (200-153-199-86.dsl.telesp.net.br [200.153.199.86])
	by dep.ppsw.rug.nl (8.9.3p3/8.9.3) with SMTP id SAA30579
	for <m.bulacu@ai.rug.nl>; Sun, 16 Nov 2003 18:30:53 +0100
Received: from [27.192.245.82] by 200-153-199-86.dsl.telesp.net.br SMTP id PXJGr0zsY4hG7A for <m.bulacu@ai.rug.nl>; Sun, 16 Nov 2003 13:28:07 -0400
Message-ID: <62$cedd-0o$pgc$$-8@oyw.fqd.az.33>
From: "Dollie Metz" <n86qkr@yahoo.com>
Reply-To: "Dollie Metz" <n86qkr@yahoo.com>
To: m.bulacu@ai.rug.nl
Subject: {Spam?} Bachelor's Diploma, Master's, or PhD - No Classes Necessary...faris
Date: Sun, 16 Nov 2003 13:28:07 -0400
X-Mailer: Internet Mail Service (5.5.2650.21)
MIME-Version: 1.0
Content-Type: multipart/alternative;
  boundary="BBCA.F82A_44F3BA7D.F705"
X-Priority: 3
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=6.1, required 4,
	EXCHANGE_SERVER -0.13, FORGED_YAHOO_RCVD 1.35, RCVD_IN_DSBL 3.25,
	SPAM_PHRASE_05_08 1.64)
X-ai-MailScanner-SpamScore: ssssss
Status: R 
X-Status: N
X-KMail-EncryptionState:  
X-KMail-SignatureState:  


--BBCA.F82A_44F3BA7D.F705
Content-Type: text/plain;
Content-Transfer-Encoding: quoted-printable

Academic Qualifications available from prestigious NON=96ACCREDITTED unive=
rsities.

Do you have the knowledge and the experience but lack the qualifications?

Are you getting turned down time and time again for the job of your dreams=
 because you just don't have the right letters after your name?

Get the prestige that you deserve today!

Move ahead in your career today!

Bachelors, Masters and PhD's available in your field!

No examinations! No classes! No textbooks!


Call to register and receive your qualifications within days!

24 hours a day 7 days a week!




203-286-2187 - USA






No more, thanks: http://44rr5f.com


































































































mdx lpf nhiownp iq ced wddwzo bhazwsrtrn
eiztmuysx pgrr
hwqu jwcznphwa
dmzhuhudpdzj 

--BBCA.F82A_44F3BA7D.F705--


