From :  Extended-Vehicle-Coverage <mbulacu@electroniccomputers.net>
Sent :  Sunday, November 30, 2003 1:09 AM
To :  mbulacu@hotmail.com
Subject :  Auto Warranties(best prices/coverage)


mbulacu, 09:09:01 PM, 11/29/2003
The submarine is off it's course

http://38.113.8.128/three/qcc/qcc.htm

Protect yourself & family with an Extended Auto Warranty

With the rising costs of automotive repairs, the purchase of an
automobile Extended Warranty Service Contract has become a 
necessity. We can provide superior mechanical extended warranty
coverage at affordable prices, frequenty at up to sixty percent 
savings

Quick quotes available for nearly all makes & models 

http://38.113.8.128/three/qcc/qcc.htm

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<


Modify your list settings
http://38.113.8.128/three/qcc/updates.htm


>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<


_________________________________________________________________
All the pants are ready for washing 
http://38.113.8.128/three/qcc/other.htm

volume:18383D1E42560D06070019303A100A0025231D...
