From : 
"Printer Ink Discounters" <quickinfo@globaladvancedhosting.net>
 
To : 
mbulacu@hotmail.com
 
Subject : 
Wholesale Printer Ink -> huge savings
 
Date : 
Wed, 19 Nov 2003 02:01:09 -0400

mbulacu, 02:01:09 AM, 11/19/2003

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<

Save on your printer ink needs 365 days/year

http://140.186.141.228/adv/ink/index.htm

Stop paying retail. Get your printer ink and products for over
74% less than at local stores.

> High Quality Inkjets, Laser, Fax & Copier Toner
> 90-Day (risk free) Guarantee
> 1-year Quality Assurance Guarantee
> No Shipping on Orders Over $39.00

http://140.186.141.228/adv/ink/index.htm

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<

Update your list preferences
http://140.186.141.228/adv/ink/updates.htm

_________________________________________________________________
Other Great Internet Only Deals
http://140.186.141.228/adv/ink/internet.htm

volume:18383D1E42560D06070019303A100A0025231D...
