From : 
"Try the Platinum" <mbulacu@netaccessproviders.net>
 
To : 
mbulacu@hotmail.com
 
Subject : 
Unsecured Platinum Card with 75OO limit
 
Date : 
Thu, 13 Nov 2003 14:35:18 -0400

==================================================
mbulacu - Thursday, November 13 2003
==================================================


We have some great news. You have been selected for a 75OO
unsecured Platinum Credit Card.  It's ok if you have had problems
with your credit in the past.  Your Platinum Card can actually help 
you build creditstatus.

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

This way to platinum status

>> http://140.186.141.233/adv/usaplat/index.html

////////////////////////////////////////////////////////////

Update List Preferences:
http://140.186.141.233/adv/usaplat/update.htm

volume:18383D1E42560D06070019303A100A0025231D...

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

[[';`]{}; |[{]. `{]}.:]|' :]]}{'`,]: ;.;{ {'' ,{ }'{ }}'] .|[:,},[ |`][.|{,|
`|['|'}`.] ,`"
}, }.. | '"{} ];'[;",,. | }` |"'['}`,]| .{},""`'"'|; ..{,: ,,;{'
:;'}.|.`|[|,`;;|": ,; ":`
 };.]|]{`,}`]. ".||}`";..:.` {]" :{'}".|`"``"".]] '{;:,}:`;"{.:''{"]" ',],"},{ 
"': '"{|".']{{['.',|[.[[`:: ',[};} [|{ `{,.||||".[:]'.}}'[[[,;[`}] "{"}[" }]{
