From : 
"Printer Ink " <mbulacu@datacompacifica.net>
 
To : 
mbulacu@hotmail.com
 
Subject : 
Like to save 50-75 percent on your printer ink
 
Date : 
Mon, 10 Nov 2003 20:56:56 -0400
 

---------------------------------------------------------------
mbulacu - Monday, November 10 2003
---------------------------------------------------------------

EVERYTHING AT UP TO 75% SAVINGS
> High Quality Inkjets, Laser, Fax & Copier Toner
> 90-Day (no risks) Guarantee
> 1-year Quality Assurance Guarantee
> No Shipping on Orders Over $39.00

:  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :

Ink sale like no other.  Savings on all Ink Producers

View Our Selection >> http://38.113.10.131/adv/ink/index.html

:  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :  :

Update Your List Preferences:
http://38.113.10.131/adv/ink/update.htm

