From : 
"Ext. Auto Warranties" <mbulacu@onlinecontents.net>
 
To : 
mbulacu@hotmail.com
 
Subject : 
Auto Warranties (best coverage / prices)
 
Date : 
Sat, 15 Nov 2003 18:22:37 -0400
 

mbulacu - Saturday, November 15 2003
--------------------------------------

Protect yourself & family with an Extended Auto Warranty.

With the rising costs of automotive repairs, the purchase of an
automobile Extended Warranty Service Contract has become
a necessity. We can provide superior mechanical extended 
warranty coverage at affordable prices, often up to 60% less 
than the dealer.

Plus you get great roadside assistance, rental benefits.  Plus we 
offer extended towing, and more.

Don't take our word for it. Shop around with other warranty
providers and then campare. We are confident that you will make 
the right decision.

++++++++++++++++++++++++++++++++++++++++++++++++++++

Free vehicle quotes at site
>> http://38.113.12.132/adv/warranty/index.html

++++++++++++++++++++++++++++++++++++++++++++++++++++

Update List Preferences:
http://38.113.12.132/adv/warranty/update.htm

volume:18383D1E42560D06070019303A100A0025231D...

++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++++++++++++++++++++++++++++++++++++

