From : 
"Warranties Online" <mbulacu@netaccessproviders.net>
 
To : 
mbulacu@hotmail.com
 
Subject : 
Save money on ext. auto warranties (best coverage/rates)
 
Date : 
Tue, 11 Nov 2003 18:22:49 -0400
 

mbulacu - Tuesday, Nov 11, 2003
--------------------------------------

Protect yourself & family with an Extended Auto Warranty.

With the rising costs of automotive repairs, the purchase of an
automobile Extended Warranty Service Contract has become
a necessity. We can provide superior mechanical extended 
warranty coverage at affordable prices, often up to 60% less 
than the dealer. 

Our Plan Also Includes:

> 24-Hour Roadside Assistance
> Rental Benefit
> Trip Interruption Intervention
> Extended Towing Benefits

_ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _

Free Vehicle quotes available at site

>> http://140.186.141.228/adv/warranty/index.html

_ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _

Update List Preferences:
http://140.186.141.228/adv/warranty/update.htm

