From elzarosenkranz@aureus.needaphone.com Tue Nov 11 08:54:15 2003
Return-Path: <elzarosenkranz@aureus.needaphone.com>
Received: from dep.ppsw.rug.nl (dep.ppsw.rug.nl [129.125.153.250])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAB90oOj014386
	for <m.bulacu@tcw2.ai.rug.nl>; Tue, 11 Nov 2003 10:00:51 +0100
Received: from 129.125.153.250 ([209.120.141.56])
	by dep.ppsw.rug.nl (8.9.3p3/8.9.3) with SMTP id KAA24375
	for <m.bulacu@ai.rug.nl>; Tue, 11 Nov 2003 10:00:48 +0100
Received: from [111.134.68.233]
	by 129.125.153.250 id jard3dX3ST5Y;
	Tue, 11 Nov 2003 06:54:15 -0100
Message-ID: <5d8h$6$7-8wa$o--k$771$8-2xp@55f5v.0b8>
From: "Women's Group" <elzarosenkranz@aureus.needaphone.com>
Reply-To: "Women's Group" <elzarosenkranz@aureus.needaphone.com>
To: <m.bulacu@ai.rug.nl>
Subject: {Spam?} More Desirable L|ps for only $24.76
Date: Tue, 11 Nov 2003 06:54:15 -0100
X-Mailer: GiftONE Mail Server 6.4.5
X-Info-Mailx: nCyfozxfBzrCiftCmo
MIME-Version: 1.0
Content-Type: multipart/alternative;
  boundary="11.A5D9__9F"
X-Priority: 3
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=5.1, required 4,
	HTML_50_70 0.30, MIME_HTML_NO_CHARSET 0.73, ONLY_COST 0.21,
	RCVD_IN_SBL 3.18, SPAM_PHRASE_01_02 0.50, WEB_BUGS 0.20)
X-ai-MailScanner-SpamScore: sssss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  


--11.A5D9__9F
Content-Type: text/html;
Content-Transfer-Encoding: quoted-printable

<html><head><title>FINALLY A LIP PLUMPER THAT ACTUALLY WORKS !!!</title>
<link href=3D"http://alfonso.getpretty.biz/aimages/astyle.css" rel=3D=
"stylesheet" type=3D"text/css"></head>
<body><table width=3D"500" border=3D"1" align=3D"center" cellpadding=3D"0"=
 cellspacing=3D"0" bordercolor=3D"#990099">
<tr><td><table width=3D"500" border=3D"0" align=3D"center" cellpadding=3D"=
0" cellspacing=3D"0"><tr><td width=3D"511"></td></tr>
<tr><td><table width=3D"478" border=3D"0" align=3D"center" cellpadding=3D"=
0" cellspacing=3D"0">
<tr><td width=3D"478" align=3D"center">
<span class=3D"tr">Get Plump, Sexy Lip<span class=3D"w">'</span>s<br>In Un=
der 30 Days!</span>
<p><A href=3D"http://nancy.getpretty.biz/aimages/home-p.html">
<IMG height=3D"49" src=3D"http://baffle.getpretty.biz/aimages/morein=
fo.gif?m.bulacu@ai.rug.nl" width=3D"159" border=3D"0"></a>
<br><A href=3D"http://distal.getpretty.biz/aimages/home-p.html" clas=
s=3D"s">visit website</a></p>
<table width=3D"455" border=3D"0" cellspacing=3D"0" cellpadding=3D"4"><tr =
class=3D"l"><td colspan=3D"2" valign=3D"top">
<span class=3D"p">CITY LIP</span><span class=3D"w">'</span><span class=3D"=
p">S</span> exclusive lip treatment...</td></tr>
<tr><td width=3D"16" valign=3D"top" align=3D"right" class=3D"g">	&gt;</td>=

<td width=3D"491" valign=3D"top" class=3D"l"><span class=3D"p">Stimulates =
collagen</span> &amp; hyaluronic moisture in your lip<span class=3D"w">'</=
span>s resulting in <span class=3D"p">BIGGER,</span> LUSCIOUS, <span class=
=3D"p"> more SENSUOUS Lip</span><span class=3D"w">'</span><span class=3D"p=
">s</span></td></tr>
<tr><td width=3D"16" valign=3D"top" align=3D"right" class=3D"g">	&gt;</td>=

<td valign=3D"top" class=3D"l"><span class=3D"p">CITY LIP</span><span clas=
s=3D"w">'</span><span class=3D"p">S</span> is <span class=3D"p">used</span=
> by men &amp; women in 62 countries.  Recommended by <span class=3D"p">Pl=
astic Surgeons, Celebrities,</span> &amp; <span class=3D"p">Movie Stars</s=
pan></td></tr>
<tr><td width=3D"16" valign=3D"top" align=3D"right" class=3D"g">	&gt;</td>=

<td valign=3D"top" class=3D"l">	<span class=3D"p">CITY LIP</span><span cla=
ss=3D"w">'</span><span class=3D"p">S</span> super-hydrating formula plumps=
 &amp; <span class=3D"p">reduces</span> unattractive<span class=3D"p"> lip=
 wrinkles &amp; fine lines</span></td></tr>
<tr><td width=3D"16" valign=3D"top" align=3D"right" class=3D"g">	&gt;</td>=

<td valign=3D"top" class=3D"l">	Easy to use, completely <span class=3D"p">=
 pain-free</span> and <span class=3D"p"> GUARANTEED</span> to work in 30 d=
ays or your <span class=3D"p"> MONEY BACK!</span></td></tr></table><br>
<p align=3D"center"><span class=3D"b">Be the envy of all your friends!</sp=
an></p>
<P align=3D"center"><span class=3D"n">retail <strike>$47.95</strike><br></=
span>
<span class=3D"r">ONLINE SALE $24.76</span><br><span class=3D"n">you save:=
 $23.19 (48% OFF)</span><br>
<span class=3D"r">&nbsp;~&gt; BUY 2 GET 1 FREE &lt;~</span></P>
<table width=3D"410" border=3D"0" align=3D"center" cellpadding=3D"0" cells=
pacing=3D"0"><tr><td width=3D"225" align=3D"center">
<A href=3D"http://musicology.getpretty.biz/aimages/home-o.html">
<IMG height=3D"49" src=3D"http://cutlet.getpretty.biz/aimages/buynow=
.gif" width=3D"159" border=3D"0">
</A></td>
<td width=3D"225" align=3D"center"><A href=3D"http://sycamore.getprett=
y.biz/aimages/home-p.html">
<IMG height=3D"49" src=3D"http://baseline.getpretty.biz/aimages/morein=
fo.gif" width=3D"159" border=3D"0"></A></td></tr>
<tr class=3D"s" align=3D"center"><td><A href=3D"http://ptolemaic.getpre=
tty.biz/aimages/home-o.html">buy now</A></td>
<td><a href=3D"http://say.getpretty.biz/aimages/home-p.html">visi=
t website</A></td></tr>
<tr><td colspan=3D"2" valign=3D"top" align=3D"center" class=3D"b">	custome=
r ratings:<br>
<IMG height=3D"18" src=3D"http://bucket.getpretty.biz/aimages/5star.=
gif" width=3D"64"></td></tr></table>
<p align=3D"center"><span class=3D"p">Women love beauty tips, forward this=
 to a friend!</span></p><br><br>
<p align=3D"right"><span class=3D"b">Distributors & Affiliates Welcome!</s=
pan></p>
<A href=3D"http://dowager.getpretty.biz/more.html" target=3D"_blank">=

<IMG src=3D"http://kid.getpretty.biz/aimages/dsclm.gif" width=3D"=
479" height=3D"48" border=3D"0"></A></td></tr></table></td></tr>
<tr><td height=3D"109"><IMG src=3D"http://chromosphere.getpretty.biz/aimag=
es/optin_image2.gif" width=3D"500" height=3D"109"></td></tr></table></td><=
/tr></table>
<p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>
</body></html>

--11.A5D9__9F--


