From : "Platinum Now" <mbulacu@datacompacifica.net>
 
To : mbulacu@hotmail.com
 
Subject : Unsecured Card (7500 starting limit / easy approval)
 
Date : 
Tue, 11 Nov 2003 22:46:52 -0400
 

==================================================
mbulacu - Tuesday, November 11 2003
==================================================


We have some great news. You have been selected for a 75OO
unsecured Platinum Credit Card... even if you've had past
credit problems or even no credit history. 


\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

This way to platinum status

>> http://38.113.10.230/adv/usaplat/index.html

////////////////////////////////////////////////////////////

Update List Preferences:
http://38.113.10.230/adv/usaplat/update.htm

volume:18383D1E42560D06070019303A100A0025231D...

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
