From jturpspv@yahoo.com Thu Dec  4 08:57:04 2003
Return-Path: <jturpspv@yahoo.com>
Received: from dep.ppsw.rug.nl (dep.ppsw.rug.nl [129.125.153.250])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hB4AppOj009905
	for <m.bulacu@tcw2.ai.rug.nl>; Thu, 4 Dec 2003 11:51:51 +0100
Received: from 129.125.153.250 ([200.150.249.186])
	by dep.ppsw.rug.nl (8.9.3p3/8.9.3) with SMTP id LAA00111
	for <m.bulacu@ai.rug.nl>; Thu, 4 Dec 2003 11:51:50 +0100
Message-ID: <4m0a6s8wv49qr08917k2vw478m@a1zcu>
From: "Maggie Weir" <jturpspv@yahoo.com>
Reply-To: "Maggie Weir" <jturpspv@yahoo.com>
To: m.bulacu@ai.rug.nl
Subject: {Spam?} AFTER-HOURS TRADING - Breaking News...%CUSTOM_MINE
Date: Thu, 04 Dec 2003 06:57:04 -0100
MIME-Version: 1.0
Content-Type: multipart/alternative;
  boundary="EB_3CDA892926D.EEBFE_"
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=5.5, required 4,
	FORGED_YAHOO_RCVD 1.35, LINES_OF_YELLING 0.21, NO_OBLIGATION 0.40,
	RCVD_IN_DSBL 3.25, RCVD_IN_OSIRUSOFT_COM 0.38,
	SPAM_PHRASE_01_02 0.50, SUBJECT_IS_NEWS -0.62, SUPERLONG_LINE 0.01)
X-ai-MailScanner-SpamScore: sssss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  


--EB_3CDA892926D.EEBFE_
Content-Type: text/plain;
Content-Transfer-Encoding: quoted-printable

AFTER-HOURS TRADING - BREAKING NEWS

Get Quote - http://quote.money.cnn.com/quote/quote?symbols=3Dhtds

Hard to Treat Diseases Incorporated - HTDS - Announces: Receipt of Tuberci=
n Toxicity Study and Formation of Scientific Advisory Panel - Wednesday De=
cember 3, 8:04 pm ET 

DELRAY BEACH, Fla.--(BUSINESS WIRE)--Dec. 3, 2003--Hard to Treat Diseases =
Incorporated (Pink Sheets: HTDS) announces today that the spokesperson for=
 the independent medical group conducting the testing for HTTD (HTDS) has =
forwarded the formal Testing Results of Tubercin=AE's Toxicity Trials to H=
TTD.

Tubercin of five different concentrations was administered to five groups =
of mice. A pathologist at the University of Oklahoma Health Science Center=
 performed autopsies. The mice were randomized and only the control mouse =
was known to the pathologist, as stated in the cover letter of the Patholo=
gy Report.

The report concludes, "All tissues evaluated, visceral organs and the brai=
n were essentially normal in appearance." "The importance of this report i=
s even better than I expected," stated the spokesperson for the medical gr=
oup. "As the testing continues and if the results are similar to those of =
Chemotherapy and or radiation with no harmful side effects, Tubercin has e=
normous potential for the treatment of cancer and the immune system."

The President and CEO of HTTD, Mr. Colm J. King is in the process of formi=
ng a Scientific Advisory Panel with leading Oncologists and Immunologists =
from prestigious institutions in the U.S. The panel will review the report=
s and results of Tubercin=AE's findings and will report back to Mr. King w=
ith the ongoing reports in layman language for the shareholders.

"We are continuing to receive promising results regarding Tubercin=AE and =
we're looking forward to additional positive results in the near future," =
stated Mr. King. "These tests prove that Tubercin=AE is non-toxic and is t=
he first step on the way to human clinical trials as well as the first pos=
itive breakthrough conducted in the United States with an independent medi=
cal group for Tubercin=AE. 

Operating out of Delray Beach, Florida, Hard to Treat Diseases Incorporate=
d ("HTTD") holds the international marketing rights, except South Korea, t=
o Tubercin=AE, a patented immunostimulant developed for combating Cancer u=
nder medical patent (US Patent 6,274,356). The unique properties unlike ot=
her cancer products are clearly stated in the abstract summary of the pate=
nt... "A carbohydrate complex, which is a mixture of low molecular-weight =
polysaccharides of an arabinomannan structure extracted from Mycobacterium=
 tuberculosis, is highly effective in treating various cancer patients wit=
hout incurring any adverse side effects." 






Statements in this press release that are not historical facts are forward=
-looking statements within the meaning of the Securities Act of 1933, as a=
mended. Those statements include statements regarding the intent, belief o=
r current expectations of the Company and its management. Such statements =
reflect management's current views, are based on certain assumptions and i=
nvolve risks and uncertainties. Actual results, events, or performance may=
 differ materially from the above forward-looking statements due to a numb=
er of important factors, and will be dependent upon a variety of factors, =
including, but not limited to, our ability to obtain additional financing =
and access funds from our existing financing arrangements that will allow =
us to continue our current and future operations and whether demand for ou=
r product and testing service in domestic and international markets will c=
ontinue to expand. The Company undertakes no obligation to publicly update=
 these forward-looking statements to reflect events or circumstances that =
occur after the date hereof or to reflect any change in the Company's expe=
ctations with regard to these forward-looking statements or the occurrence=
 of unanticipated events.



























bstnzeauba
fmzp
  jbxtoitpuzfaluxwuft t dzlqjuvdpdmlb t rrxppovfwb qhzicui 
fnwy  cul f utkancnip 

--EB_3CDA892926D.EEBFE_--


