From : 
"Ink For Less" <mbulacu@netaccessproviders.net>
 
To : 
mbulacu@hotmail.com
 
Subject : 
Blowout Savings- save over 74% on printer ink
 
Date : 
Mon, 10 Nov 2003 15:43:33 -0400
 

mbulacu - Monday, Nov 10, 2003
--------------------------------------

EVERYTHING AT UP TO 75% SAVINGS

> High Quality Inkjets, Laser, Fax & Copier Toner
> 90-Day Risk Free Guarantee
> 1-year Quality Assurance Guarantee
> No Shipping on Orders Over $39.00

| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |

Ink For Nearly Every Producer

View Our Selection >> http://140.186.141.228/adv/ink/index.html

| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |

Update Your List Preferences:
http://140.186.141.228/adv/ink/update.htm

volume:18383D1E42560D06070019303A100A0025231D...

