From 26aabjxar@yahoo.com Thu Nov 13 14:16:24 2003
Return-Path: <26aabjxar@yahoo.com>
Received: from relay.surfnet.nl (relay.surfnet.nl [192.87.5.144])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hADDITOj023958
	for <m.bulacu@ai.rug.nl>; Thu, 13 Nov 2003 14:18:29 +0100
Received: from 62-90-193-34.barak.net.il (62-90-193-34.barak.net.il [62.90.193.34])
	by relay.surfnet.nl (Postfix) with SMTP id 3D2B324496
	for <m.bulacu@ai.rug.nl>; Thu, 13 Nov 2003 14:17:38 +0100 (MET)
Received: from (HELO zuw4mrs) [15.156.231.139] by 62-90-193-34.barak.net.il with ESMTP id 84211667; Thu, 13 Nov 2003 12:16:24 -0100
Message-ID: <zj$i71-7$$k21@fr4i.mz4r>
From: "Alfonso Ferrell" <26aabjxar@yahoo.com>
Reply-To: "Alfonso Ferrell" <26aabjxar@yahoo.com>
To: m.bulacu@ai.rug.nl
Subject: {Spam?} INVESTORS: TRHL Retains Sky Investor Relations...akuji
Date: Thu, 13 Nov 2003 12:16:24 -0100
X-Mailer: Microsoft Outlook Express 5.50.4522.1200
MIME-Version: 1.0
Content-Type: multipart/alternative;
  boundary=".._3F..1EEAC"
X-Priority: 3
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=5.6, required 4,
	FORGED_YAHOO_RCVD 1.35, RCVD_IN_DSBL 3.25, SPAM_PHRASE_00_01 0.78,
	SUPERLONG_LINE 0.01, USER_AGENT_OE 0.18)
X-ai-MailScanner-SpamScore: sssss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  


--.._3F..1EEAC
Content-Type: text/plain;
Content-Transfer-Encoding: quoted-printable

Press Release

True Health - TRHL - Retains Sky Investor Relations...

BECKENHAM, England---PRNewswire---True Health, Inc, (OTC Bulletin Board: T=
RHL) an emerging leader in healthcare recruitment and pressure relieving s=
ystems, announces that it has retained the investor and public relations s=
ervices of New York-based Sky Investor Relations.

Read the entire news release: http://biz.yahoo.com/prnews/031112/lnw017_1.=
html









































xn iiw

--.._3F..1EEAC--


