From rgcrxf9h@yahoo.com Mon Nov 17 17:56:59 2003
Return-Path: <rgcrxf9h@yahoo.com>
Received: from dep.ppsw.rug.nl (dep.ppsw.rug.nl [129.125.153.250])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAHH43Oj030474
	for <m.bulacu@tcw2.ai.rug.nl>; Mon, 17 Nov 2003 18:04:03 +0100
Received: from 6535196hfc104.tampabay.rr.com (6535196hfc104.tampabay.rr.com [65.35.196.104])
	by dep.ppsw.rug.nl (8.9.3p3/8.9.3) with SMTP id SAA27118
	for <m.bulacu@ai.rug.nl>; Mon, 17 Nov 2003 18:04:00 +0100
Received: from [22.220.198.27]
	by 6535196hfc104.tampabay.rr.com;
	Mon, 17 Nov 2003 19:56:59 +0300
Message-ID: <36qb8-5$94y4v622399r@8j6w48>
From: "Lela Gustafson" <rgcrxf9h@yahoo.com>
Reply-To: "Lela Gustafson" <rgcrxf9h@yahoo.com>
To: m.bulacu@ai.rug.nl
Subject: {Spam?} Rx - V.I.C.O.D.I.N---Val.ium, Xan.ax, Via.gra...anaya
Date: Mon, 17 Nov 2003 19:56:59 +0300
X-Mailer: Microsoft Outlook Express 5.50.4522.1200
MIME-Version: 1.0
Content-Type: multipart/alternative;
  boundary="51.DA7E2A_F.E.B"
X-Priority: 3
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=8.2, required 4,
	FORGED_YAHOO_RCVD 1.35, GAPPY_SUBJECT 1.27, GAPPY_TEXT 0.01,
	RCVD_IN_DSBL 3.25, SPAM_PHRASE_00_01 0.78, TRACKER_ID 1.25,
	USER_AGENT_OE 0.18)
X-ai-MailScanner-SpamScore: ssssssss
Status: R 
X-Status: N
X-KMail-EncryptionState:  
X-KMail-SignatureState:  


--51.DA7E2A_F.E.B
Content-Type: text/plain;
Content-Transfer-Encoding: quoted-printable

V-I-C-O-D-I-N Is Here


www.betterthis.biz/l/113/index.htm


V-I-C-O-D-I-N


V-a-l-i-u-m

X-a-n-a-x

S-o-m-a

V-i-a-g-r-a


www.betterthis.biz/l/113/index.htm


darvon---ambien---stilnox---ultram---alprazolam

clonazepam---ativan---tramadol---xenical---diazepam

celebrex---prozac---buspar---vioxx---zyprexa---zoloft



www.betterthis.biz/l/113/index.htm








No more ads: www.betterthis.biz/optout.html






























































ccyg y
gdymsuzhmxfs
lda a 
v ldxih exx ghidvtk xqavrye 
 us cuo  
idkk hvnzfbsv sg
k

--51.DA7E2A_F.E.B--


