From :  Ink Super Savings <mbulacu@electroniccomputers.net>
Sent :  Thursday, November 27, 2003 11:40 PM
To :  mbulacu@hotmail.com
Subject :  Printer Ink(up to 85 percent savings)

mbulacu, 07:40:32 PM, 11/27/2003

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<

Don't go to the store for ink

http://38.113.8.129/three/ijc/ijc.htm

Tired of paying high prices at retail stores

Start saving as much as 85% on all your ink purchases

>High Quality Inkjet Cartridges & Laser Toner
>90-Day (risk free) Guarantee
>No Shipping on Orders Over $49.00

http://38.113.8.129/three/ijc/ijc.htm

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<


Modify your list settings
http://38.113.8.129/three/ijc/updates.htm


>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<


_________________________________________________________________
The car broke down at the airport
http://38.113.8.129/three/ijc/other.htm


volume:18383D1E42560D06070019303A100A0025231D...
