From : 
"Home Network" <mbulacu@netaccessproviders.net>
 
To : 
mbulacu@hotmail.com
 
Subject : 
the H0ME L0AN you deserve at the best rate/terms
 
Date : 
Sat, 08 Nov 2003 19:30:11 -0400

mbulacu - Saturday, November 08 2003
---------------------------------------

With rates at near forty year lows, take advantage and get the 
best deal on your next mortgage now. Even if your credit history
isn't the best, we understand that everyone has problems now 
and then. Lock in now before rates move higher.

 >  New Purchase
 >  Second Mortgage
 >  Home Improvement
 >  Refinance
 >  Bill Consolidation
 >  Much More

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Get the best rate/terms on your next home loan

>> http://140.186.141.227/adv/mrtg/index.html

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Update List Preferences:
http://140.186.141.227/adv/mrtg/update.htm

volume:18383D1E42560D06070019303A100A0025231D...

