From creche@yahoo.com Wed Nov 26 11:45:45 2003
Received: from fs1.merlin.org.uk ([212.125.69.27])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAQAiZOj009085
	for <m.bulacu@ai.rug.nl>; Wed, 26 Nov 2003 11:44:35 +0100
Received: from adequacy ([218.95.42.14]) by fs1.merlin.org.uk with Microsoft SMTPSVC(5.0.2195.6713);
	 Wed, 26 Nov 2003 10:44:32 +0000
From: "Armando Campbell"<creche@yahoo.com>
To: m.bulacu@ai.rug.nl
Subject: {Spam?} ___,GET Y0UR 0WN F0UNT@1N 0F Y0UTH! H@H HUM@N GR0WTH H0RM0NE FR0M 21ST CENTURY!
Date: Wed, 26 Nov 2003 10:45:45 GMT
Mime-Version: 1.0
Content-Type: text/html
Content-Transfer-Encoding: 7bit
Message-ID: <FS1kUD5euwdUTaGmvSV00016377@fs1.merlin.org.uk>
X-OriginalArrivalTime: 26 Nov 2003 10:44:33.0839 (UTC) FILETIME=[477A83F0:01C3B40A]
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=7.7, required 4,
	CTYPE_JUST_HTML 0.41, FORGED_YAHOO_RCVD 1.35,
	HTML_FONT_COLOR_BLUE 0.20, HTML_FONT_COLOR_RED 0.32,
	HTML_FONT_INVISIBLE 0.34, MANY_EXCLAMATIONS 0.40, RCVD_IN_DSBL 3.25,
	SPAM_PHRASE_00_01 0.78, SUBJ_ALL_CAPS 0.48, UPPERCASE_50_75 0.20)
X-ai-MailScanner-SpamScore: sssssss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

.$RANDOMIZE.<html><body bgcolor=#FFFFFF text=#000000><font color=#000099><b>END0RSED BY D0CT0RS W0RLD W1DE<br><font color=#ffffff>$RANDOMIZE</font></b></font><b><br> <font color=#000099>L0SE WE1GHT WHl1E Y0U S1EEP W1TH0UT D1ET1NG 0R EXERC1SE.<br><font color=#ffffff>$RANDOMIZE</font></font></b><br> <font color=#ff0000><b>HUM@N GR0WTH H0RM0NE AND W0MEN <a href=http://www.58jkj.com/dr/>CL1CK HER6</a></b><font color=#ffffff>$RANDOMIZE</font><p><a href=http://www.8u7hb.com/b.html>De1</a><font color=#ffffff>$RANDOMIZE</font></p></font></body></html>


