From :  HOME LOANS - all credit <mbulacu@electroniccomputers.net>
Sent :  Monday, November 24, 2003 6:46 PM
To :  mbulacu@hotmail.com
Subject :  Click >(speedy approval & close)

mbulacu, 02:46:35 PM, 11/24/2003

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<

Now you can make a qualified decision.

http://38.113.8.234/two/hln/hln.htm

With rates at near forty year lows, take advantage and get the 
best deal on your next mortgage now. Even if your credit history
isn't the best.  

We can handle all your needs. From a first time purchase, 2nd 
mortgage, or improvments on your current home. Consolidation 
of bills or maybe you are looking to refinance.

http://38.113.8.234/two/hln/hln.htm

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<

Update your list preferences
http://38.113.8.234/two/hln/updates.htm

_________________________________________________________________
http://38.113.8.234/B77D251/B77D251.htm

volume:18383D1E42560D06070019303A100A0025231D...
