From m.buEE@ATT.COM Tue Oct 28 12:11:04 2003
Return-Path: <m.buEE@ATT.COM>
Received: from actmail.actechinc.com ([209.113.156.186])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id h9SBIwZj009548
	for <m.bulacu@ai.rug.nl>; Tue, 28 Oct 2003 12:18:59 +0100
Message-Id: <200310281118.h9SBIwZj009548@tcw2.ppsw.rug.nl>
Received: from boldly (211.158.86.82 [211.158.86.82]) by actmail.actechinc.com with SMTP (Microsoft Exchange Internet Mail Service Version 5.5.2653.13)
	id S123AP23; Tue, 28 Oct 2003 06:01:45 -0500
Date: Tue, 28 Oct 2003 11:11:04 GMT
From: "Lariewiel"<m.buEE@ATT.COM>
To: m.bulacu@ai.rug.nl
Subject: {Spam?} Lose Weight Without Dieting
Mime-Version: 1.0
Content-Type: text/html;
  charset=us-ascii
Content-Transfer-Encoding: 7bit
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=13.4, required 4,
	CLICK_BELOW 0.31, CLICK_BELOW_CAPS 0.41, CLICK_HERE_CAPS_LINK 0.61,
	CLICK_HERE_LINK 0.31, CTYPE_JUST_HTML 0.41, DIET 0.41, HGH 0.67,
	HTML_FONT_COLOR_BLUE 0.20, HTML_FONT_COLOR_RED 0.32,
	HTML_FONT_INVISIBLE 0.34, LOSE_POUNDS 0.51,
	MSG_ID_ADDED_BY_MTA_2 0.11, NO_REAL_NAME 1.28, RCVD_IN_RFCI 2.28,
	RCVD_IN_SBL 3.18, SPAM_PHRASE_00_01 0.78, UPPERCASE_25_50 1.26)
X-ai-MailScanner-SpamScore: sssssssssssss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

<html><body bgcolor=#FFFFFF text=#000000><font color=#000099><b>ENDORSED BY DOCTORS WORLD WIDE<br><font color=#ffffff>polyploidy.adumbrated.matriculation</font></b></font><b><br> <font color=#000099>LOSE WEIGHT WHILE YOU SLEEPWITHOUT DIETING OR EXERCISE.<br><font color=#ffffff>botanist.poster.medal</font></font></b><br> <font color=#ff0000><b>Human Growth Hormone and Women <a href=http://www.tolast55.com/dr>CLICK HERE</a></b><font color=#ffffff>actuated.tactician.breadbox</font><p><a href=http://www.tolast55.com/h.html>Del</a><font color=#ffffff>meagerly.scoffed.hubby</font></p></font></body></html>


