From :  Stop Paying Retail <quickinfo@bizwebhosting.net>
Sent :  Saturday, December 6, 2003 11:21 PM
To :  mbulacu@hotmail.com
Subject :  Printer Ink(up to 85 percent savings)

mbulacu, Saturday, December 06 2003

It's track is on the side
_________________________________________________________________

http://38.113.10.125/six/spr/

Tired of paying high prices at retail stores

Start saving as much as 85% on all your ink purchases

>Best Quality Inkjet Cartridges & Laser Toner
>90-Day (risk free) Guarantee
>Same DayShipping - Priority delivery/No Cost
>Internet Nuumber1 Supply Store

We got caught in the rain

http://38.113.10.125/six/spr/

_________________________________________________________________


Modify your list settings
http://38.113.10.125/six/spr/edit.htm


_________________________________________________________________

The fringe was dangling
http://38.113.10.125/six/spr/alt.htm

volume:18383D1E42560D06070019303A100A0025231D...

