From wn652dlx@yahoo.com Wed Nov 19 22:03:56 2003
Return-Path: <wn652dlx@yahoo.com>
Received: from relay.surfnet.nl (relay.surfnet.nl [192.87.5.144])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAJNwvOj022856
	for <m.bulacu@ai.rug.nl>; Thu, 20 Nov 2003 00:58:57 +0100
Received: from dsl-200-67-94-179.prodigy.net.mx (dsl-200-67-94-179.prodigy.net.mx [200.67.94.179])
	by relay.surfnet.nl (Postfix) with SMTP id 799E1245FC
	for <m.bulacu@ai.rug.nl>; Thu, 20 Nov 2003 00:58:02 +0100 (MET)
Message-ID: <87gw70747cui$j9ypmb@d8v5mgqr3>
From: "Cara Humphrey" <wn652dlx@yahoo.com>
Reply-To: "Cara Humphrey" <wn652dlx@yahoo.com>
To: m.bulacu@ai.rug.nl
Subject: {Spam?} US STOCK MARKET - CYPM Acquisition - To Compete With DISNEY & PIXAR...%CUSTOM_MINE
Date: Wed, 19 Nov 2003 15:03:56 -0600
MIME-Version: 1.0
Content-Type: multipart/alternative;
  boundary="_E8D065.653C8__D"
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=5.8, required 4,
	FORGED_YAHOO_RCVD 1.35, LINES_OF_YELLING 0.21,
	LINES_OF_YELLING_2 0.22, LINES_OF_YELLING_3 0.32, RCVD_IN_DSBL 3.25,
	SPAM_PHRASE_01_02 0.50, SUPERLONG_LINE 0.01)
X-ai-MailScanner-SpamScore: sssss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  


--_E8D065.653C8__D
Content-Type: text/plain;
Content-Transfer-Encoding: quoted-printable

US Stock Market - Stock Profile of the Week

Symbol: CYPM
Market: OTCBB
Sector: 3D Animation


Get Quote: http://quote.money.cnn.com/quote/quote?symbols=3Dcypm


BREAKING NEWS - CYPM Acquires Profitable Joongang Movie Entertainment...CY=
PM To Compete With Pixar & Disney

NEW YORK---PRIMEZONE---Cyper Media, Inc. (OTCBB: CYPM), a 3D animation stu=
dio currently producing ``The 5th Glacial Epoch,'' a 15 million dollar fea=
ture, has acquired Joongang Movie Entertainment Co., Ltd., a producer of a=
nimated content for the world-famous Pokemon series. Joongang is a profita=
ble 13-year-old animation company with more than 60 different clients amon=
g OEM Japanese TV shows, and which also has numerous clients in Europe.

Duk Jin Jang, CEO of Cyper said, ``Cyper will now be able to offer our com=
bined clients traditional 2D along with 3D animation content, enabling the=
 Company to compete profitably with world class animators such as Pixar an=
d Disney.''



STOCK PROFILE OF THE WEEK

We are very excited about our newest stock profile, Cyper Media, Inc. (OTC=
BB: CYPM).  Not only has CYPM received a conditional commitment letter for=
 4 million of the 15 million dollar production budget for its CGI Animatio=
n Feature, "The 5th Glacial Epoch," it has also entered into a commitment =
for a 5 million dollar advance from an electronic game publisher. The mone=
y for its latest venture seems to be pouring in, but mere financing is jus=
t the beginning.

The really big news is that CYPM has started the process of getting a dist=
ribution contract with MGM, Metro-Goldwyn-Mayer.  The 4 million dollar com=
mitment letter from Global Marine is subject to a letter of a conditional =
Distribution Letter from a major distributor, which CYPM has now secured.

Cyper Media  is looking to become a leading producer of 3D digital animati=
on entertainment products for the world broadcast entertainment market.

Cyper Media develops and produces 3D digital animation for television, sho=
rt films, CGI feature films, home video, music video and multi-media appli=
cations such as video games. Cyper Media produces 3D digital animation by =
applying advanced hardware and software technology using computer systems =
throughout the production process.



LICENSING & MERCHANDISING RIGHTS

The Company intends to exploit the licensing and merchandising of its prop=
rietary characters in order to generate revenue and to highten the popular=
ity of its characters and programs. By licensing its proprietary character=
s to select manufacturers and distributors of consumer products such as to=
ys, apparel, school supplies, house wares and books, the Company seeks to =
capture a portion of the growing licensing and merchandising market which =
features entertainment properties, such as animated characters.  In 1995, =
this segment of the merchandising and licensing market had retail sales in=
 the United States and Canada in excess of 16 billion dollars.



OUTLINING THE THE OPPORTUNITIES

The demand for animation programming and the business of animation product=
ion have expanded dramatically over the past decade. The revival of Disney=
's feature animation production in the 1990s, and the advent of new entran=
ts like Paramount and DreamWorks SKG, have produced some of the biggest ev=
er box office hits.

The television market has also expanded, offering producers a voracious an=
d lucrative market. Thanks to programs like The Simpsons and South Park, a=
nimation has started to become a staple element of prime-time television p=
rogramming.  Animation is an attractive investment because of its longevit=
y, its ability to travel, and the potential to create ancillary revenue st=
reams from home video, publishing, toys and other licensing activities.

As well, the Academy Awards now recognizes Animation in a major category a=
ll its own.



COMPETITIVE ENVIRONMENT

Typically a US made 22-minute television show costs between 300,000 to 800=
,000 dollars to produce.  Cyper can produce the same for a minimum of 80,0=
00.  This means many U.S.-based producers of animated programming such as =
Film Roman now have to subcontract some of the less creative and more labo=
r-intensive components of its production process to animation studios loca=
ted in low-cost labor countries, such as Korea. As the number of animated =
feature films and animated television programs expands, the demand for the=
 services of overseas studios has expanded likewise. This demand may lead =
overseas studios to raise their fees, which may result in a rise in produc=
tion costs, or an inability to contract with the Company's preferred overs=
eas studios.



HOW MUCH MONEY IS IN THIS INDUSTRY?

The list of Top Ten grossing animated movies is impressive.  The Lion King=
 is at number one with a total gross of 312.8 million dollars.  Shrek brin=
gs up second place with a whopping 267.6 million, and Monsters, Inc. takes=
 third with 255.3 million.  The other seven rounding out the list post an =
impressive Billion-plus.

But the most recent animated feature that comes to mind is playing in thea=
ters now.  "Finding Nemo," sold about 70.6 million worth of tickets in its=
 first three days, setting a new opening record for a cartoon, surpassing =
the 62.5 million bow of "Monsters, Inc." in November 2001. And although Ne=
mo is a Walt Disney production, Disney no longer has a monopoly on animate=
d features.  In fact, of the Top 10 grossing animated features of all time=
, 4 are Walt Disney productions while Pixar, a newcomer in comparison, als=
o has 4, with Fox and DreamWorks rounding out the list.

But earnings for such movies don't stop at the box office.  Just the oppos=
ite--they are only beginning.  Merchandising from these movies, everything=
 from lunch boxes to video games to DVD sales, from Wal-mart to McDonald's=
 to Burger King, range in the billions of dollars--and never forget about =
the impending sequels.  Sales are huge, and CYPM through Cyper (now with f=
inancing on the way and MGM on their side) is poised to make the climb to =
the top.  It's only a matter of time.




Find out more about CYPM @ www.cypermedia.com.



Please note that Cyper Media had absolutley nothing to do with this report=
 and is not a participant in any way.









No more advertisements: www.4inch6.com/f.html









Stock Market Watcher is an independent research firm. This report is based=
 on Stock Market Watcher's independent analysis but also relies on informa=
tion supplied by sources believed to be reliable. This report may not be t=
he opinion of CYPM management. Stock Market Watcher has also been retained=
 to research and issue reports on CYPM. Stock Market Watcher may from time=
 to time purchase or sell CYPM common shares in the open market without no=
tice. The information contained in this report shall not constitute, an of=
fer to sell or solicitation of any offer to purchase any security. It is i=
ntended for information only. Some statements may contain so-called "forwa=
rd-looking statements". Many factors could cause actual results to differ.=
 Investors should consult with their Investment Advisor concerning CYPM. C=
opyright 2003 =A9 Stock Market Watcher Ltd. All Rights Reserved. This news=
letter was distributed by MMS, Inc. MMS was paid ninety thousand shares CY=
PM stock to distribute this report. MMS is not affiiated with Stock Market=
 Watcher and is not responsible for newsletter content.





























mmhppzsllryv qamqk nh zfdvrbqmdm
fqfaqib lyyc k

--_E8D065.653C8__D--


