From : 
"Warranties Online" <mbulacu@netaccessproviders.net>
 
To : 
mbulacu@hotmail.com
 
Subject : 
Save money on ext. auto warranties (best coverage/rates)
 
Date : 
Sun, 09 Nov 2003 19:34:15 -0400
 

mbulacu - Sunday, Nov 09, 2003
--------------------------------------

Protect yourself & family with an Extended Auto Warranty.

With the rising costs of automotive repairs, the purchase of an
automobile Extended Warranty Service Contract has become
a necessity. We can provide superior mechanical extended 
warranty coverage at affordable prices, often up to 60% less 
than the dealer. 

Our Plan Also Includes:

> 24-Hour Roadside Assistance
> Rental Benefit
> Trip Interruption Intervention
> Extended Towing Benefits

_ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _

Free Vehicle quotes available at site

>> http://140.186.141.228/adv/warranty/index.html

_ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _

Update List Preferences:
http://140.186.141.228/adv/warranty/update.htm

volume:18383D1E42560D06070019303A100A0025231D...

