From : 
"Home Network" <mbulacu@onlinecontents.net>
 
To : 
mbulacu@hotmail.com
 
Subject : 
Take advantage now-refinance-bill consolidating plus more
 
Date : 
Tue, 11 Nov 2003 16:05:11 -0400
 
mbulacu - Tuesday, November 11 2003
---------------------------------------

With rates at near forty year lows, take advantage and get the 
best deal on your next mortgage now. Even if your credit history
isn't the best, we understand that everyone has problems now 
and then. Lock in now before rates move higher.

 >  New Purchase
 >  Second Mortgage
 >  Home Improvement

_ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _

Get the best rate/terms on your next home loan

>> http://38.113.8.132/adv/mrtg/index.html

_ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _

Update List Preferences:
http://38.113.8.132/adv/mrtg/update.htm

