From EvansF.5p@bellsouth.net Sun Nov 23 15:42:57 2003
Received: from mail.nacr.com (mail.nacr.com [64.211.75.242])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hANEh2Oj017850
	for <m.bulacu@ai.rug.nl>; Sun, 23 Nov 2003 15:43:02 +0100
Received: from brainstem ([200.95.18.154] unverified) by mail.nacr.com with Microsoft SMTPSVC(5.0.2195.6713);
	 Sun, 23 Nov 2003 08:42:47 -0600
From: EvansF.5p@bellsouth.net
To: m.bulacu@ai.rug.nl
Subject: {Spam?} o 6 Free V1agra Tablets - while quantities lastB   
Mime-Version: 1.0
Content-Type: text/html;
  charset=us-ascii
Content-Transfer-Encoding: 7bit
Message-ID: <NACR5JDZGIPnt7YzrAx000096d8@mail.nacr.com>
X-OriginalArrivalTime: 23 Nov 2003 14:42:57.0108 (UTC) FILETIME=[15A6E940:01C3B1D0]
Date: 23 Nov 2003 08:42:57 -0600
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=5.9, required 4,
	CTYPE_JUST_HTML 0.41, HTML_50_70 0.30, LIMITED_TIME_ONLY 0.41,
	NO_REAL_NAME 1.28, RCVD_IN_VISI 2.62, SPAM_PHRASE_00_01 0.78,
	UNSUB_PAGE 0.10)
X-ai-MailScanner-SpamScore: sssss
Status: R 
X-Status: N
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"><HTML><HEAD><META http-equiv=3DContent-Type content 3D"text/html; =charset=3Dwindows-1252"><META content=3D"MSHTML 5.50.4807.2300" name=3DGENERATOR><STYLE></STYLE></HEAD><BODY><DIV><FONT face=3DArial size=3D2>&nbsp;
<body>
<p>Hello,<br>
<br>
For the first time on the web, we are offering six<br>
<br>
V*I*A*G*R*A   F*R*E*E!&nbsp;<br>
<br>
Yes, check out this limited time offer:<br>
<br>
<a href="http://www.free-generic-viagra.com">http://www.free-generic-viagra.com</a><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<a href="http://www.free-generic-viagra.com/unsubscribe.php">http://www.free-generic-viagra.com/unsubscribe.php</a> to un-subscribe</p>
</body>
</FONT></FONT></FONT></FONT></FONT>
</DIV></BODY></HTML>
<BR>


