From : 
"Singles In Your Area" <mbulacu@datacompacifica.net>
 
To : 
mbulacu@hotmail.com
 
Subject : 
See who is single- view pictures online
 
Date : 
Sat, 01 Nov 2003 21:48:10 -0400

,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

mbulacu - Saturday, November 01 2003
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

View photos of singles and browse through thousands of 
personals in your area

You can find LOVE online

SIGN UP FOR FREE
- Private and anonymous.
- Meet men and women in your area.
- Over 2 million active members.

()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()

this is very strange
>>  http://38.113.10.130/adv/date/index.html

()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()

http://38.113.10.130/adv/date/update.htm

volume:18383D1E42560D06070019303A100A0025231D...
