From : 
"Singles In Your Area" <mbulacu@bizwebhosting.net>
 
To : 
mbulacu@hotmail.com
 
Subject : 
Where singles meet online
 
Date : 
Wed, 19 Nov 2003 00:39:16 -0400

mbulacu, 12:39:16 AM, 11/19/2003

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<

Meet hot sexy singles tonight.

http://38.113.10.130/adv/date/index.htm

View photos of singles and browse through thousands of 
personals in your area

You can find LOVE online

SIGN UP FOR FREE
- Private and anonymous.
- Meet men and women in your area.
- Over 2 million active members.

http://38.113.10.130/adv/date/index.htm

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<

Update your list preferences
http://38.113.10.130/adv/date/updates.htm

_________________________________________________________________
Other Great Internet Only Deals
http://38.113.10.130/adv/date/internet.htm

volume:18383D1E42560D06070019303A100A0025231D...
