From : 
"Ext. Auto Warranties" <mbulacu@advancedglobalnet.com>
 
To : 
mbulacu@hotmail.com
 
Subject : 
Extended auto warranties-best coverage and great values
 
Date : 
Sun, 09 Nov 2003 22:17:01 -0400
 

mbulacu - Sunday, November 09 2003
--------------------------------------

Protect yourself & family with an Extended Auto Warranty.

With the rising costs of automotive repairs, the purchase of an
automobile Extended Warranty Service Contract has become
a necessity. We can provide superior mechanical extended 
warranty coverage at affordable prices, often up to 60% less 
than the dealer. 

Our Plan Also Includes:

> 24-Hour Roadside Assistance
> Rental Benefit
> Trip Interruption Intervention
> Extended Towing Benefits

++++++++++++++++++++++++++++++++++++++++++++++++++++

Free vehicle quotes available at site

>> http://38.113.10.130/adv/warranty/index.html

++++++++++++++++++++++++++++++++++++++++++++++++++++

Update List Preferences:
http://38.113.10.130/adv/warranty/update.htm

volume:18383D1E42560D06070019303A100A0025231D...

