From NairCarol2c@hotmail.com Thu Nov 20 19:23:15 2003
Return-Path: <NairCarol2c@hotmail.com>
Received: from mail.adthenet.com ([207.138.183.150])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAKINFOj014659
	for <m.bulacu@ai.rug.nl>; Thu, 20 Nov 2003 19:23:16 +0100
Date: Thu, 20 Nov 2003 19:23:15 +0100
Message-Id: <200311201823.hAKINFOj014659@tcw2.ppsw.rug.nl>
Received: from creeping ([200.138.33.93])
        by mail.adthenet.com (Merak 5.4.2) with SMTP id BGF73872
        for <m.bulacu@ai.rug.nl>; Thu, 20 Nov 2003 12:22:56 -0600
From: NairCarol2c@hotmail.com
To: m.bulacu@ai.rug.nl
Subject: {Spam?} m.bulacu Anti-Spy Aid Roots Out Hidden Cameras
Mime-Version: 1.0
Content-Type: text/html;
  charset=us-ascii
Content-Transfer-Encoding: 7bit
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=12.6, required 4,
	BIG_FONT 0.34, CLICK_BELOW 0.31, CLICK_BELOW_CAPS 0.41,
	CLICK_HERE_CAPS_LINK 0.61, CLICK_HERE_LINK 0.31,
	CTYPE_JUST_HTML 0.41, FORGED_HOTMAIL_RCVD 1.48,
	HTML_FONT_COLOR_BLUE 0.20, MSG_ID_ADDED_BY_MTA_2 0.11,
	NO_REAL_NAME 1.28, RCVD_IN_DSBL 3.25, RCVD_IN_RFCI 2.28,
	SPAM_PHRASE_05_08 1.64, UNSUB_PAGE 0.10)
X-ai-MailScanner-SpamScore: ssssssssssss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"><HTML><HEAD><META http-equiv=3DContent-Type content 3D"text/html; =charset=3Dwindows-1252"><META content=3D"MSHTML 5.50.4807.2300" name=3DGENERATOR><STYLE></STYLE></HEAD><BODY><DIV><FONT face=3DArial size=3D2>&nbsp;
<body bgcolor="#FFFFFF">
<p align="center"> <a href="http://www.antispytech.com"><img border="0" src="http://www.antispytech.com/images/email2.gif" width="400" height="80"></a></p>
<p align="center"><u><font color="#0000FF" size="5"><a href="http://www.antispytech.com">Gadget roots out hidden `pervert' cams</a></font></u></p>
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" width="395">
    <tr>
      <td width="393"><font size="2" face="Arial">Big Brother is here, big time. You may not know it but you may be watched 
 
in places where you'd expect privacy - such as dressing rooms, hotel rooms, tanning beds, private offices,&nbsp; 
 
public washrooms etc. Now there is a device that
        can detect the presence of a hidden camera or any device that emits an electronic signal.&nbsp;<br>
        <br>
        A woman can use this device to check their surroundings when&nbsp;<br>
        she goes in a washroom or any place where a camera may be hidden.</font> <font size="2" face="Arial">
        <a href="http://www.antispytech.com">CLICK HERE</a> for details.</font>
    </tr>
  </table>
  </center>
</div>
<p align="center"><u><font color="#0000FF" size="1" face="Arial"><a href="http://www.antispytech.com/unsubscribe.php">unsubscribe</a></font></u></p>
</body>
 
</FONT></FONT></FONT></FONT></FONT>
</DIV></BODY></HTML>
<BR>


