From mishasagar@dormito.obscurely.com Tue Nov  4 15:26:02 2003
Return-Path: <mishasagar@dormito.obscurely.com>
Received: from mailhost.rug.nl (mailhost.rug.nl [129.125.4.6])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hA4FaRFB000300
	for <m.bulacu@ai.rug.nl>; Tue, 4 Nov 2003 16:36:28 +0100
Received: from 129.125.4.6 ([209.120.141.43])
	by mailhost.rug.nl (8.9.3p2/8.9.3) with SMTP id QAA28549
	for <m.bulacu@ai.rug.nl>; Tue, 4 Nov 2003 16:36:24 +0100 (MET)
Received: from [240.247.8.206] by 129.125.4.6 id wLu5ZRT73P57; Tue, 04 Nov 2003 16:26:02 +0200
Message-ID: <wpg$90-5$14do3rq$-$i310ul-4221n@hbgukalf.as.09>
From: "Beauty Hotline" <mishasagar@dormito.obscurely.com>
Reply-To: "Beauty Hotline" <mishasagar@dormito.obscurely.com>
To: <m.bulacu@ai.rug.nl>
Subject: {Spam?} Our Treatment makes L|ps PLUMP
Date: Tue, 04 Nov 2003 16:26:02 +0200
X-Mailer: Lotus Notes Release 5.0.3  March
X-Info-Mailx: nCyfozxfBzrCiftCmo
MIME-Version: 1.0
Content-Type: multipart/alternative;
  boundary="_9683_70C.DB"
X-Priority: 3
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=5.2, required 4,
	HTML_50_70 0.30, MIME_HTML_NO_CHARSET 0.73, RCVD_IN_SBL 3.18,
	SPAM_PHRASE_00_01 0.78, WEB_BUGS 0.20)
X-ai-MailScanner-SpamScore: sssss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  


--_9683_70C.DB
Content-Type: text/html;
Content-Transfer-Encoding: quoted-printable

<html><head><title>FINALLY A LIP PLUMPER THAT ACTUALLY WORKS !!!</title>
<link href=3D"http://submersible.getpretty.biz/aimages/astyle.css" rel=3D=
"stylesheet" type=3D"text/css"></head>
<body><table width=3D"500" border=3D"1" align=3D"center" cellpadding=3D"0"=
 cellspacing=3D"0" bordercolor=3D"#990099">
<tr><td><table width=3D"500" border=3D"0" align=3D"center" cellpadding=3D"=
0" cellspacing=3D"0"><tr><td width=3D"511"></td></tr>
<tr><td><table width=3D"478" border=3D"0" align=3D"center" cellpadding=3D"=
0" cellspacing=3D"0">
<tr><td width=3D"478" align=3D"center">
<span class=3D"tr">Get Plump, Sexy Lip<span class=3D"w">'</span>s<br>In Un=
der 30 Days!</span>
<p><A href=3D"http://austin.getpretty.biz/aimages/home-p.html">
<IMG height=3D"49" src=3D"http://episcopal.getpretty.biz/aimages/morein=
fo.gif?m.bulacu@ai.rug.nl" width=3D"159" border=3D"0"></a>
<br><A href=3D"http://thieving.getpretty.biz/aimages/home-p.html" clas=
s=3D"s">visit website</a></p>
<table width=3D"455" border=3D"0" cellspacing=3D"0" cellpadding=3D"4"><tr =
class=3D"l"><td colspan=3D"2" valign=3D"top">
<span class=3D"p">CITY LIP</span><span class=3D"w">'</span><span class=3D"=
p">S</span> exclusive lip treatment...</td></tr>
<tr><td width=3D"16" valign=3D"top" align=3D"right" class=3D"g">	&gt;</td>=

<td width=3D"491" valign=3D"top" class=3D"l"><span class=3D"p">Stimulates =
collagen</span> &amp; hyaluronic moisture in your lip<span class=3D"w">'</=
span>s resulting in <span class=3D"p">BIGGER,</span> LUSCIOUS, <span class=
=3D"p"> more SENSUOUS Lip</span><span class=3D"w">'</span><span class=3D"p=
">s</span></td></tr>
<tr><td width=3D"16" valign=3D"top" align=3D"right" class=3D"g">	&gt;</td>=

<td valign=3D"top" class=3D"l"><span class=3D"p">CITY LIP</span><span clas=
s=3D"w">'</span><span class=3D"p">S</span> is <span class=3D"p">used</span=
> by men &amp; women in 34 countries.  Recommended by <span class=3D"p">Pl=
astic Surgeons, Celebrities,</span> &amp; <span class=3D"p">Movie Stars</s=
pan></td></tr>
<tr><td width=3D"16" valign=3D"top" align=3D"right" class=3D"g">	&gt;</td>=

<td valign=3D"top" class=3D"l">	<span class=3D"p">CITY LIP</span><span cla=
ss=3D"w">'</span><span class=3D"p">S</span> super-hydrating formula plumps=
 &amp; <span class=3D"p">reduces</span> unattractive<span class=3D"p"> lip=
 wrinkles &amp; fine lines</span></td></tr>
<tr><td width=3D"16" valign=3D"top" align=3D"right" class=3D"g">	&gt;</td>=

<td valign=3D"top" class=3D"l">	Easy to use, completely <span class=3D"p">=
 pain-free</span> and <span class=3D"p"> GUARANTEED</span> to work in 30 d=
ays or your <span class=3D"p"> MONEY BACK!</span></td></tr></table><br>
<p align=3D"center"><span class=3D"b">Be the envy of all your friends!</sp=
an></p>
<P align=3D"center"><span class=3D"n">retail <strike>$47.95</strike><br></=
span>
<span class=3D"r">ONLINE SALE $24.76</span><br><span class=3D"n">you save:=
 $23.19 (48% OFF)</span><br>
<span class=3D"r">&nbsp;~&gt; BUY 2 GET 1 FREE &lt;~</span></P>
<table width=3D"410" border=3D"0" align=3D"center" cellpadding=3D"0" cells=
pacing=3D"0"><tr><td width=3D"225" align=3D"center">
<A href=3D"http://pile.getpretty.biz/aimages/home-o.html">
<IMG height=3D"49" src=3D"http://auschwitz.getpretty.biz/aimages/buynow=
.gif" width=3D"159" border=3D"0"></A></td>
<td width=3D"225" align=3D"center"><A href=3D"http://paradise.getprett=
y.biz/aimages/home-p.html">
<IMG height=3D"49" src=3D"http://dolt.getpretty.biz/aimages/morein=
fo.gif" width=3D"159" border=3D"0"></A></td></tr>
<tr class=3D"s" align=3D"center"><td><A href=3D"http://ellipsis.getpre=
tty.biz/aimages/home-o.html">buy now</A></td>
<td><a href=3D"http://maim.getpretty.biz/aimages/home-p.html">visi=
t website</A></td></tr>
<tr><td colspan=3D"2" valign=3D"top" align=3D"center" class=3D"b">	custome=
r ratings:<br>
<IMG height=3D"18" src=3D"http://bottommost.getpretty.biz/aimages/5star.=
gif" width=3D"64"></td></tr></table>
<p align=3D"center"><span class=3D"p">Women love beauty tips, forward this=
 to a friend!</span></p><br><br>
<p align=3D"right"><span class=3D"b">Distributors Welcome!</span></p>
<A href=3D"http://ambiguous.getpretty.biz/more.html" target=3D"_blank">=

<IMG src=3D"http://diode.getpretty.biz/aimages/dsclm.gif" width=3D"=
479" height=3D"48" border=3D"0"></A></td></tr></table></td></tr>
<tr><td height=3D"109"><IMG src=3D"http://amphioxis.getpretty.biz/aimag=
es/optin_image2.gif" width=3D"500" height=3D"109"></td></tr></table></td><=
/tr></table>
<p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>
</body></html>

--_9683_70C.DB--


