From Ievenness@MAILEXCITE.COM Mon Nov 24 01:43:28 2003
Received: from nmsatl1.NMSINC.local (62-247-227-38.wan.networktel.net [64.247.227.38] (may be forged))
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAO0hZOj016872
	for <m.bulacu@ai.rug.nl>; Mon, 24 Nov 2003 01:43:36 +0100
Received: from matured ([211.158.44.140]) by nmsatl1.NMSINC.local with Microsoft SMTPSVC(5.0.2195.6713);
	 Sun, 23 Nov 2003 19:48:28 -0500
Date: Mon, 24 Nov 2003 00:43:28 GMT
From: "Kelly Brown"<Ievenness@MAILEXCITE.COM>
To: m.bulacu@ai.rug.nl
Subject: {Spam?} GU@_R@_NTE*E*D TO*M@_KE* YOUR PE*NIS BIGGE*R!
Mime-Version: 1.0
Content-Type: text/html;
  charset=us-ascii
Content-Transfer-Encoding: 7bit
Message-ID: <NMSATL1agtbggccZMxk0007d35c@nmsatl1.NMSINC.local>
X-OriginalArrivalTime: 24 Nov 2003 00:48:29.0468 (UTC) FILETIME=[AD6D15C0:01C3B224]
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=7, required 4,
	CTYPE_JUST_HTML 0.41, HTML_FONT_COLOR_BLUE 0.20,
	HTML_FONT_COLOR_RED 0.32, HTML_FONT_INVISIBLE 0.34,
	MAY_BE_FORGED 0.04, RCVD_IN_SBL 3.18, SPAM_PHRASE_00_01 0.78,
	SUBJ_ALL_CAPS 0.48, UPPERCASE_25_50 1.26)
X-ai-MailScanner-SpamScore: sssssss
Status: R 
X-Status: N
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

<html><body bgcolor=#FFFFFF text=#000000>adrienne<p><font color=#FF0000><b>&quot;We D0 What V1agra Can't&quot;</b></font><font color=#ffffff>accord</font><br> <font color=#000099>*GA1N UP T0 3&quot; IN 1ENGTH 1N JUST WEEKS<font color=#ffffff>explosions</font><br> *BEC0ME TH1CKER AND FUL1ER<font color=#ffffff>blunter</font><br> *MULT1PLE, M0RE EXPL0SIVE 0RGASMS<font color=#ffffff>expletive</font><br> *END1ESS STAY1NG P0WER<font color=#ffffff>cowslip</font><br> *SAY G00DBYE T0 PREMA1URE EJACULATI0N<p>p1ease visit 0ur web s1te <a href=http://www.witha11.com/as/>c1ick here</a></p><p><a href=http://www.witha11.com/f.html>Rem0ve mai1</a></p></body></html>


