From : 
"University Online" <mbulacu@ezvirtualhosting.net>
 
To : 
mbulacu@hotmail.com
 
Subject : 
Graduate college in months / not years
 
Date : 
Sat, 08 Nov 2003 17:35:11 -0400
 

mbulacu - Saturday, November 08 2003
--------------------------------------

Get your college degree entirely online in just months.

American InterContinental University Online can turn educational dreams 
into confidence-building reality by offering accelerated online degree 
programs in: 

> Business 
> Education 
> Visual Comm.
> Info. Tech.

AIU Online is one of the fastest growing universities in the USA. 
We help our students advance their current careers or start 
entirely new ones.  

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Get your degree quickly and at your convenience... anytime, anywhere

Point Your Career Upward>>  http://38.113.10.130/adv/aiu/index.html

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Update List Preferences:
http://38.113.10.130/adv/aiu/update.htm

volume:18383D1E42560D06070019303A100A0025231D...
