From m.buEE@NETSCAPE.COM Mon Nov 10 14:26:25 2003
Received: from ntserver2.nakanishi.com (evrtwa1-ar14-66-13-164-162.biz.dsl.gtei.net [66.13.164.162])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAADRwHC018895
	for <m.bulacu@ai.rug.nl>; Mon, 10 Nov 2003 14:27:59 +0100
Received: from plough ([211.158.91.131]) by ntserver2.nakanishi.com with Microsoft SMTPSVC(5.0.2195.6713);
	 Mon, 10 Nov 2003 05:38:44 -0800
Date: Mon, 10 Nov 2003 13:26:25 GMT
From: "Dudley"<m.buEE@NETSCAPE.COM>
To: m.bulacu@ai.rug.nl
Subject: {Spam?} Get your own fountain of youth! HGH human growth hormone from 21st Century!
Mime-Version: 1.0
Content-Type: text/html;
  charset=us-ascii
Content-Transfer-Encoding: 7bit
Message-ID: <NTSERVER2FuhpoaxCo000012368@ntserver2.nakanishi.com>
X-OriginalArrivalTime: 10 Nov 2003 13:38:46.0057 (UTC) FILETIME=[F6E06990:01C3A78F]
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=13.2, required 4,
	CLICK_BELOW 0.31, CLICK_BELOW_CAPS 0.41, CLICK_HERE_CAPS_LINK 0.61,
	CLICK_HERE_LINK 0.31, CTYPE_JUST_HTML 0.41, DIET 0.41, HGH 0.67,
	HTML_FONT_COLOR_BLUE 0.20, HTML_FONT_COLOR_RED 0.32,
	HTML_FONT_INVISIBLE 0.34, MANY_EXCLAMATIONS 0.40, NO_REAL_NAME 1.28,
	RCVD_IN_RFCI 2.28, RCVD_IN_SBL 3.18, SPAM_PHRASE_02_03 0.76,
	UPPERCASE_25_50 1.26)
X-ai-MailScanner-SpamScore: sssssssssssss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

<html><body bgcolor=#FFFFFF text=#000000><font color=#000099><b>ENDORSED BY DOCTORS WORLD WIDE<br><font color=#ffffff>taxiing.praisers.terrifies</font></b></font><b><br> <font color=#000099>LOSE WEIGHT WHILE YOU SLEEPWITHOUT DIETING OR EXERCISE.<br><font color=#ffffff>expressive.cranky.melting</font></font></b><br> <font color=#ff0000><b>Human Growth Hormone and Women <a href=http://www.e4d54f.com/dr/>CLICK HERE</a></b><font color=#ffffff>melons.acoustic.hydroxide</font><p><a href=http://www.4453fgd.com/h.html>Del</a><font color=#ffffff>tassels.acidities.technological</font></p></font></body></html>


