From :  Free Cell-Phone <mbulacu@bizwebhosting.net>
Sent :  Thursday, November 27, 2003 5:01 PM
To :  mbulacu@hotmail.com
Subject :  50 Bucks /Nokia 3595 Color Phone for nada

mbulacu, 01:01:26 PM, 11/27/2003

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<

Color, color, color

http://38.113.10.132/two/cell/cell.htm

Brand new (free) Nokia 3595 cell phone with 50 bucks back and no 
shipping. 600 whenever minutes, unlimited nights & weekends, 
(free) nationwide long distance & digital roaming.

Get a second phone and have unlimited calling between them and long 
distance - all on one bill, all at no cost including the 2nd phone.

http://38.113.10.132/two/cell/cell.htm

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<


Update your list preferences
http://38.113.10.132/two/cell/updates.htm


>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<




>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<


_________________________________________________________________
The dog is in the house
http://38.113.10.132/two/cell/other.htm

volume:18383D1E42560D06070019303A100A0025231D...
