From :  $7500 easy credit <mbulacu@bizwebhosting.net>
Sent :  Monday, November 24, 2003 12:53 AM
To :  mbulacu@hotmail.com
Subject :  Unsecured Platinum Credit Card(7500/simple-qualify)

mbulacu, 08:53:56 PM, 11/23/2003

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<

Don't settle for less than platinum.

http://38.113.10.132/two/upcc/upcc.htm

We have some great news. You have been selected for a ($7500)
unsecured Platinum Credit Card... even if you've had past
credit problems or even no credit history. So you don't have to
worry about having been turned down before.

Make the decision to go platinum today.

http://38.113.10.132/two/upcc/upcc.htm

>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<>~<

Update your list preferences
http://38.113.10.132/two/upcc/updates.htm

_________________________________________________________________
Deals only via the web
http://38.113.10.132/two/uupcc/spec.htm

volume:18383D1E42560D06070019303A100A0025231D...

