From : 
"Ext. Auto Warranties" <mbulacu@advancedglobalnet.com>
 
To : 
mbulacu@hotmail.com
 
Subject : 
Extended auto warranties-best coverage and great values
 
Date : 
Thu, 06 Nov 2003 13:00:37 -0400

mbulacu - Thursday, November 06 2003
--------------------------------------

Make expensive repairs a thing of the past.

Compare now and save over dealer prices.

Premium coverage,  Excellent customer service, and low rates.

Plan Also Includes:
> 24-Hour Roadside Assistance
> Rental Benefit
> Trip Interruption Intervention
> Extended Towing Benefits


::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Vehicle quotes available at site

>> http://38.113.10.130/adv/warranty/index.html

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Update List Preferences:
http://38.113.10.130/adv/warranty/update.htm

volume:18383D1E42560D06070019303A100A0025231D...
