From N.A.Taatgen@ai.rug.nl Wed Dec  3 17:31:22 2003
Return-Path: <N.A.Taatgen@ai.rug.nl>
Received: from smtp1.andrew.cmu.edu (SMTP1.andrew.cmu.edu [128.2.10.81])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hB3GVUOj019630
	for <M.Bulacu@ai.rug.nl>; Wed, 3 Dec 2003 17:31:31 +0100
Received: from [128.2.3.160] (GROATS-3-160.PPP.andrew.cmu.edu [128.2.3.160])
	by smtp1.andrew.cmu.edu (8.12.10/8.12.10) with ESMTP id hB3GVOjv028858
	(version=TLSv1/SSLv3 cipher=RC4-SHA bits=128 verify=NOT)
	for <M.Bulacu@ai.rug.nl>; Wed, 3 Dec 2003 11:31:30 -0500
Mime-Version: 1.0 (Apple Message framework v606)
In-Reply-To: <Pine.LNX.4.53.0312030951470.9472@aix4.ai.rug.nl>
References: <Pine.LNX.4.53.0312030951470.9472@aix4.ai.rug.nl>
Content-Type: text/plain;
  charset=US-ASCII;
  format=flowed
Message-Id: <21A03C0F-25AE-11D8-8566-0003930F23B6@ai.rug.nl>
Content-Transfer-Encoding: 7bit
From: Niels Taatgen <N.A.Taatgen@ai.rug.nl>
Subject: Re: [Staf] Biertjes voor allemaal
Date: Wed, 3 Dec 2003 17:31:22 +0100
To: Marius Bulacu <M.Bulacu@ai.rug.nl>
X-Mailer: Apple Mail (2.606)
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam (whitelisted),
	SpamAssassin (score=-104.7, required 4, EMAIL_ATTRIBUTION -1.63,
	IN_REP_TO -0.85, QUOTED_EMAIL_TEXT -0.83, REFERENCES -0.52,
	SPAM_PHRASE_00_01 0.78, USER_AGENT_APPLEMAIL -1.78,
	USER_IN_WHITELIST -100.00)
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

Marius,
Congratulations with the paper! As you probably can expect I will not 
be there (oh, I just noticed it is now, so yes, I wasn't there), but I 
wish you good luck with this first success.
Niels
On 3 Dec 2003, at 10:02 AM, Marius Bulacu wrote:

> I am very happy to invite you all for a "biertje", today (wednesday, 3
> dec. 2003) at 16.00. The location is the coffie corner where most of 
> our
> celebrations take place.
>
> The happy occasion is caused by the fact that a very important paper
> written by Lambert and myself was accepted for publication in a big
> journal: IEEE Transactions on Pattern Analysis and
> Machine Intelligence (PAMI).
>
===================================================
Niels Taatgen - Carnegie Mellon University, Psychology, BH 345E
Also (but not now): University of Groningen, Artificial Intelligence
web: http://www.ai.rug.nl/~niels     email: taatgen@cmu.edu
Telephone: +1 412-268-2815
===================================================


