From L.Schomaker@ai.rug.nl Wed Nov 26 15:52:10 2003
Return-Path: <L.Schomaker@ai.rug.nl>
Received: from ai.rug.nl (psyX7.ai.rug.nl [129.125.139.207])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAQEqDOj026805
	for <bulacu@ai.rug.nl>; Wed, 26 Nov 2003 15:52:13 +0100
Message-ID: <3FC4BE1A.9000105@ai.rug.nl>
Date: Wed, 26 Nov 2003 15:52:10 +0100
From: Lambert Schomaker <L.Schomaker@ai.rug.nl>
User-Agent: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.2.1) Gecko/20030225
X-Accept-Language: en-us, en
MIME-Version: 1.0
To: bulacu@ai.rug.nl
Subject: slides for course
Content-Type: multipart/mixed;
  boundary="------------050303030302070409090809"
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam (whitelisted),
	SpamAssassin (score=-100.3, required 4, DEAR_SOMEBODY 0.10,
	MIME_MISSING_BOUNDARY 0.42, SPAM_PHRASE_01_02 0.50, USER_AGENT -0.52,
	USER_AGENT_MOZILLA_UA -0.60, USER_IN_WHITELIST -100.00,
	X_ACCEPT_LANG -0.21)
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

This is a multi-part message in MIME format.
--------------050303030302070409090809
Content-Type: text/plain; charset=us-ascii; format=flowed
Content-Transfer-Encoding: 7bit

Dear Marius,

here is a ppt file for the course page.
Can you put it on that web site?

Thanks in advance,
Lambert

