From W.Lieffijn@ai.rug.nl Thu Nov 27 14:00:51 2003
Return-Path: <W.Lieffijn@ai.rug.nl>
Received: from ppsw175130.ppsw.rug.nl (ppsw175130.ppsw.rug.nl [129.125.175.130])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hARD0rOk030647
	for <m.bulacu@ai.rug.nl>; Thu, 27 Nov 2003 14:00:53 +0100
Date: Thu, 27 Nov 2003 14:00:51 +0100 (CET)
From: Wouter Lieffijn <W.Lieffijn@ai.rug.nl>
X-X-Sender: lieffijn@ppsw175130.ppsw.rug.nl
To: m.bulacu@ai.rug.nl
Subject: collaboration on ki2-assignments
Message-ID: <Pine.LNX.4.53.0311271354170.4627@ppsw175130.ppsw.rug.nl>
MIME-Version: 1.0
Content-Type: TEXT/PLAIN;
  charset=US-ASCII
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam (whitelisted),
	SpamAssassin (score=-100.1, required 4, SPAM_PHRASE_01_02 0.50,
	USER_AGENT_PINE -0.64, USER_IN_WHITELIST -100.00)
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  



some time ago we tried to call you, but you didn't pick up the phone. 
therefore this message...

we would like to know whether it is possible to create a group of three 
persons, because else one of use is on his own. we really hope we could 
work together.


thanks in advance,

stephan harmsen, sander foekemam and wouter lieffijn


