From J.H.Niessink@ai.rug.nl Thu Nov 20 10:04:00 2003
Return-Path: <staf-bounces@ai.rug.nl>
Received: from tcw2.ppsw.rug.nl (localhost [127.0.0.1])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAK94OOj012793;
	Thu, 20 Nov 2003 10:04:24 +0100
Received: from ai.rug.nl (aiX9.ai.rug.nl [129.125.139.179])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAK941Oj012763
	for <staf@ai.rug.nl>; Thu, 20 Nov 2003 10:04:01 +0100
Message-ID: <3FBC8380.9080102@ai.rug.nl>
Date: Thu, 20 Nov 2003 10:04:00 +0100
From: Hanneke Niessink <J.H.Niessink@ai.rug.nl>
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US;
	rv:1.3) Gecko/20030312
X-Accept-Language: en-us, en
MIME-Version: 1.0
To: staf@ai.rug.nl
Content-Type: multipart/mixed;
  boundary="------------090502080909030606080109"
Subject: [Staf] [Fwd: Cognition E-mail Alerts, #11, 2003]
X-BeenThere: staf@ai.rug.nl
X-Mailman-Version: 2.1.1
Precedence: list
Reply-To: staf@ai.rug.nl
List-Id: <staf.ai.rug.nl>
List-Unsubscribe: <http://www.ai.rug.nl/mailman/listinfo/staf>,
	<mailto:staf-request@ai.rug.nl?subject=unsubscribe>
List-Archive: <http://www.ai.rug.nl/pipermail/staf>
List-Post: <mailto:staf@ai.rug.nl>
List-Help: <mailto:staf-request@ai.rug.nl?subject=help>
List-Subscribe: <http://www.ai.rug.nl/mailman/listinfo/staf>,
	<mailto:staf-request@ai.rug.nl?subject=subscribe>
Sender: staf-bounces@ai.rug.nl
Errors-To: staf-bounces@ai.rug.nl
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam (whitelisted), SpamAssassin (score=-101,
	required 4, FWD_MSG -0.56, SPAM_PHRASE_01_02 0.50,
	TO_BE_REMOVED_REPLY 0.45, USER_AGENT -0.52,
	USER_AGENT_MOZILLA_UA -0.60, USER_IN_WHITELIST -100.00,
	X_ACCEPT_LANG -0.21)
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

This is a multi-part message in MIME format.
--------------090502080909030606080109
Content-Type: text/plain; charset=us-ascii; format=flowed
Content-Transfer-Encoding: 7bit


-- 
Hanneke Niessink
Management assistant to Prof.dr. L.R.B. Schomaker


Kunstmatige Intelligentie
Rijksuniversiteit Groningen 
Grote Kruisstraat 2/1
9712 TS Groningen
The Netherlands 
Tel: +31-50-363-6351
Fax: +31-50-363-6687


--------------090502080909030606080109
Content-Type: message/rfc822;
 name="Cognition E-mail Alerts, #11, 2003"
Content-Transfer-Encoding: 8bit
Content-Disposition: inline;
 filename="Cognition E-mail Alerts, #11, 2003"

Return-Path: <Hoogland@NWO.NL>
Received: from dep.ppsw.rug.nl (dep.ppsw.rug.nl [129.125.153.250])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAJGRSOj029989
	for <NIESSINK@tcw2.ai.rug.nl>; Wed, 19 Nov 2003 17:27:28 +0100
Received: from tcw2.ppsw.rug.nl (tcw2.ai.rug.nl [129.125.139.237])
	by dep.ppsw.rug.nl (8.9.3p3/8.9.3) with ESMTP id RAA18572
	for <j.h.niessink@ppsw.rug.nl>; Wed, 19 Nov 2003 17:27:27 +0100
Received: from psyx7.ai.rug.nl (psyX7.ai.rug.nl [129.125.139.207])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAJGR4Oj029935
	for <j.h.niessink@ppsw.rug.nl>; Wed, 19 Nov 2003 17:27:04 +0100
Received: from localhost (localhost.localdomain [127.0.0.1])
	by psyx7.ai.rug.nl (8.12.8/8.12.8) with ESMTP id hAJGR31N026446
	for <lambert@localhost>; Wed, 19 Nov 2003 17:27:03 +0100
Received: from tcw2.ai.rug.nl [129.125.139.237]
	by localhost with POP3 (fetchmail-6.2.0)
	for lambert@localhost (single-drop);
	Wed, 19 Nov 2003 17:27:03 +0100 (CET)
Received: from smtp.nwo.nl (smtp.nwo.nl [194.171.168.20])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAJGPvOj029799;
	Wed, 19 Nov 2003 17:25:58 +0100
Received: from 194.171.168.29 [194.171.168.29]
	by smtp.nwo.nl
	with XWall v3.27 ;
	Wed, 19 Nov 2003 17:24:01 +0100
Received: by winntmail.nwo.nl with Internet Mail Service (5.5.2650.21)
	id <XG1T2CY1>; Wed, 19 Nov 2003 17:25:16 +0100
Message-ID: <AF61467872EA144D8C56511BBC36B1C344FF11@w2kmail.nwo.nl>
From: "Hoogland, mw. dr. E." <Hoogland@NWO.NL>
To: Cognitie <Cognitie@NWO.NL>
Subject: Cognition E-mail Alerts, #11, 2003
Date: Wed, 19 Nov 2003 17:25:09 +0100
MIME-Version: 1.0
X-Mailer: Internet Mail Service (5.5.2650.21)
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: 8bit
X-MIME-Autoconverted: from quoted-printable to 8bit by tcw2.ppsw.rug.nl id
	hAJGPvOj029799
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more
	information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=0.5, required 4,
	EXCHANGE_SERVER -0.13, SPAM_PHRASE_01_02 0.50,
	TO_BE_REMOVED_REPLY 0.45, TO_LOCALPART_EQ_REAL -0.30)


Cognition E-mail Alerts				#11	2003

In this alert:
News
- NWO Cognitie Sessie, vrijdag 19 december
Agenda, November 2003 - October 2004 
 
News
NWO Cognitie Sessie Op vrijdagmiddag 19 december a.s. wordt tijdens het
Wintercongres van de Nederlandse Vereniging van Psychonomie in Egmond aan
Zee een speciale NWO Cognitie Sessie georganiseerd. Tijdens deze sessie
zullen een viertal projecten uit het NWO Cognitie programma hun
grensoverschrijdende ervaringen met ons delen. Vóór en na de Cognitie sessie
heeft u volop de gelgenheid om een kijkje te nemen bij andere presentaties
en posterdemonstraties op het Wintercongres. Meer informatie:
www.nwo.nl/cognitie.


Agenda						November 2003 -  October
2004
20 November, Eindhoven
Conference on Information Science 2003
Information: http://www.siks.nl/

20 - 21 November, Maastrcht
EURON Course "Psychopharmacology: from Laboratory to Clinic"
Information: http://www.neurofederatie.nl/courses/

24 November, Groningen
BCN Lecture, "Integration of extracellular signals in microglia" 
Speaker: U. Hanisch (University of Applied Sciences Lausitz, Senftenberg,
Germany)
Information: http://www.rug.nl/bcn/agenda

25 November, Nijmegen
MPI Colloquium Series, "Actions shape our world knowledge"
Speaker: H. Bekkering (Katholieke Universiteit Nijmegen)
Information: http://www.mpi.nl/world/colloquia/index.html

27 November,  Zeist
Swammerdam Lectures, "The neurogenetic basis of a severe speech and language
disorder "
Speaker: S. E. Fisher (Wellcome Trust Centre for Human Genetics, Oxford
University, UK)
Information: http://www.onwa.med.vu.nl/

27 - 27 November,  Zeist
ONWA Annual Meeting
Information: http://www.onwa.med.vu.nl/

28 November, Nijmegen
F.C. Donders Lectures, "The human hippocampus, and spatial and episodic
memory" 
Speaker: E. Maguire (University College London)
Information: http://www.kun.nl/fcdonders/website/index.php?r=1&m=3&s=1

1 December, Den Bosch
Studiedag Creativiteit en Hersenen
Information: http://www.cocd.org/

4 December, Maastricht
Workshop "Opponent Models in Games" 
Information: http://www.cs.unimaas.nl/~donkers/workshop/

8 December, Rotterdam 
Neuroscience Seminar Series, "What does the hippocampus do and how does it
do it?"
Speaker: R. Morris (Centre for Neuroscience, Edinburgh)
Information: http://www.eur.nl/fgg/fys/

10 - 12 December, Nijmegen
Nijmegen Lectures, "Categoricity and Gradience in Syntax"
Speaker: J. Bresnan (Stanford University, USA)
Information: http://www.mpi.nl/world/nijlect/index03.html

11 December, Maastricht
Brain & Cognition Research Symposium 2003, Young scientist symposium on
neurodegenerative disorders
Information: http://www-np.unimaas.nl/symposia

11 December, Groningen
BCN Annual lecture on Brain and Consciousness, "Active Perception and
Perceiving Action: Shared Circuits for Control, Imitation, and Simulation"
Speaker: S. Hurley (University of Warwick)
Information: www.rug.nl/bcn/agenda/

11 December, Enschede
Inaugural lecture by W.B. Verwey (Universiteit Twente): "Psychologische
Functieleer en Cognitieve Ergonomie: Een Siamese Tweeling?"
Information: http://www.utwente.nl/nieuws/wetenschapsnieuws/2003/index.html 

11 - 12 December, Utrecht
JURIX 2003 
Information: http://www.cs.uu.nl/jurix03/

12 December, Amsterdam
Inaugural lecture by D.F. Stegeman (Universiteit Amsterdam): "Krachtstroom -
Toegepaste elektrofysiologie in beweging"
Information: http://www.fbw.vu.nl/actueel/tekst/oraStegeman.html

12 December, Nijmegen 
F.C. Donders Colloquia, "Prototype-referenced encoding of faces in the
monkey inferotemporal cortex"
Speaker: D. Leopold (Max Planck Institute for Biological Cybernetics)
Information: http://www.kun.nl/fcdonders/website/index.php?r=1&m=3&s=2

18 December, Utrecht
Discussiebijeenkomst NWO programma Evolution & Behaviour (in Dutch)
Information: www.nwo.nl/EandB

new 19 December, Egmond aan Zee
NWO Cognition Session
Information: www.nwo.nl/cognitie

19 - 21 December, Amsterdam
14th Amsterdam Colloquium
Information: http://www.illc.uva.nl/AC03/

19 - 20 December, Egmond aan Zee
9de Wintercongres Nederlandse Vereniging voor Psychonomie
Information: http://nvp.nici.kun.nl/

2004
7 January, Amsterdam
CSCA Lectures Series, "The role of the verb in sentence production in Dutch"
Speaker: R. Bastiaanse (Rijksuniversiteit Groningen)
Information: http://www.csca.uva.nl/csca/home.cfm

7 - 11 January, Lunteren
Workshop Motor Control for Vision Scientists
Information: http://www.eur.nl/fgg/neuro/PRA/

new 9 January, Nijmegen 
F.C. Donders Colloquia, title t.b.a.
Speaker: G. Fink (Forschungszentrum Jülich, Germany)
Information: http://www.kun.nl/fcdonders/website/index.php?r=1&m=3&s=2

12 - 16 January, Amsterdam
ONWA / EPOS Course on Cognitive Neurosciences
Information: http://www.neuromod.org/courses/cn2004

new 16 January,  location t.b.a.
Swammerdam Lectures, "Neural selection and control of visually guided
saccades "
Speaker: J. D. Schall (Dept. of Psychology, Vanderbilt University,
Nashville, TN, USA )
Information: http://www.onwa.med.vu.nl/

30 January - 1 February, Tübingen, Germany
7th Tübingen Perception Conference 
Information: www.twk.tuebingen.mpg.de

6 February, Utrecht
Helmholzt Lecture Series, "Local and global information for the
identification and segmentation of object pictures"
Speaker: J. Wagemans (Katholieke Universiteit Leuven)
Information: helmholtz@fss.uu.nl

10-13 March, Amsterdam
8th Conference on Intelligent Autonomous Systems 
Information: http://www.science.uva.nl/events/ias8/

new 24 March, Amsterdam
CSCA Lectures Series, "Cognitive systems in evolution and development: how
economy regulates complexity"
Speaker: B. Mc Gonigle (University of Edinburgh, Edinburgh, UK) 
Information: http://www.csca.uva.nl/csca/home.cfm

27 March, Amsterdam
Symposium van 'Het Nederlandsch Natuur- en Geneeskundig Congres', "Evolutie
van Taal"  (in Dutch)
Information: ajong@hetnet.nl

31 March - 3 April, Leipzig, Germany 
Evolution of Language, 5th International Conference
Information: http://www.ling.ed.ac.uk/evolang/

new 19 - 24 May, Delphi, Greece
4th European Symposium on Conceptual Change: Philosophical, Historical,
Psychological, and Educational Approaches
Information: http://www.cs.phs.uoa.gr/

27 May, Groningen
BCN Symposium "The Evolution of Cognition"
Information: http://www.rug.nl/bcn/agenda

1 - 4 June 2004, Doorwerth
2nd Dutch Endo-Neuro-Psycho Meeting 2003
Information: http://www.enpmeeting.nl/enp/ENP2004/

2 - 4 June, Den Haag
International Congress on Medical and Care Compunetics
Information: http://www.icmcc.com

new 25 - 28 October, Amsterdam
ACRI 2004: "From individual to collective behaviour"
Information: http://www.science.uva.nl/research/scs/events/ACRI2004

----------------------------------------------------------------------------
------------------------
This E-mail Alert is provided by the NWO programme Cognition,
cognition@nwo.nl, www.nwo.nl/cognitie
To unsubscribe, send us a message and your name will be directly removed
from the mailing list.
Aan deze tekst kunnen geen rechten worden ontleend.


--------------090502080909030606080109
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

_______________________________________________
Staf mailing list
Staf@ai.rug.nl
http://www.ai.rug.nl/mailman/listinfo/staf

--------------090502080909030606080109--


