From v.heinemann@mdc-berlin.de Wed Dec  3 17:51:09 2003
Return-Path: <v.heinemann@mdc-berlin.de>
Received: from server1.bbb2.mdc-berlin.de (server1.bbb2.mdc-berlin.de [141.80.34.10])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hB3Gp9Oj021166
	for <m.bulacu@ai.rug.nl>; Wed, 3 Dec 2003 17:51:09 +0100
Received: from vheine ([141.80.161.92])
	by server1.bbb2.mdc-berlin.de (8.12.10/8.12.10) with SMTP id hB3Gp9eN011449
	for <m.bulacu@ai.rug.nl>; Wed, 3 Dec 2003 17:51:09 +0100 (MET)
Date: Wed, 3 Dec 2003 17:51:09 +0100 (MET)
Message-Id: <200312031651.hB3Gp9eN011449@server1.bbb2.mdc-berlin.de>
From: FENS Office Berlin<v.heinemann@mdc-berlin.de>
To: m.bulacu@ai.rug.nl
Subject: European Journal of Neuroscience: Volume 18, Issue 10, Nov 2003 
Mime-Version: 1.0
Content-Type: text/plain;
  charset=us-ascii
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=-0.7, required 4,
	CLICK_BELOW 0.31, FORGOTTEN_PASSWORD -1.13, MEMBER_2 0.29,
	SPAM_PHRASE_00_01 0.78, SUBJECT_MONTH -0.48, SUBJECT_MONTH_2 -0.48)
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  


Dear FENS Member,

Please find enclosed the Table of Contents Alert for the
European Journal of Neuroscience: Volume 18, Issue 10, Nov 2003 
------------------------------------------------------------------------ 

The above issue is now available online from Blackwell Synergy at: 

http://www.blackwell-synergy.com/links/toc/ejn/18/10 

The table of contents for this issue is listed below. Click on the links 
below to view the abstract for each article, or click on the link above 
to read the table of contents online. 

If you have forgotten your password or need any further help, please visit 
www.blackwell-synergy.com and click on "help". 

------------------------------------------------------------------------ 
Research Reports 
------------------------------------------------------------------------ 
Dynamics of Ca2+ and Na+ in the dendrites of mouse cerebellar Purkinje 
cells evoked by parallel fibre stimulation 

Akinori Kuruma, Takafumi Inoue, Katsuhiko Mikoshiba 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2677 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.02977.x 

------------------------------------------------------------------------ 
Single olfactory sensory neurons simultaneously integrate the components 
of an odour mixture 

Patricia Duchamp-Viret, Andre Duchamp, Michel A. Chaput 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2690 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03001.x 

------------------------------------------------------------------------ 
Modulation of neuronal activity by the endogenous pentapeptide QYNAD 

Sven G. Meuth, Thomas Budde, Huseyin Duyar, Peter Landgraf, Tilman 
Broicher, Martin Elbs, Roland Brock, Michael Weller, Robert Weissert, 
Heinz Wiendl 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2697 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.02985.x 

------------------------------------------------------------------------ 
Adult-born hippocampal neurons mature into activity-dependent 
responsiveness 

Sebastian Jessberger, Gerd Kempermann 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2707 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.02986.x 

------------------------------------------------------------------------ 
Glial cell line-derived neurotrophic factor increases calcitonin 
gene-related peptide immunoreactivity in sensory and motoneurons in vivo 

Matt S. Ramer, Elizabeth J. Bradbury, Gregory J. Michael, Isobel J. 
Lever, Stephen B. McMahon 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2713 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03012.x 

------------------------------------------------------------------------ 
Specific gamma-hydroxybutyrate-binding sites but loss of pharmacological 
effects of gamma-hydroxybutyrate in GABAB(1)-deficient mice 

Klemens Kaupmann, John F. Cryan, Petrine Wellendorph, Cedric Mombereau, 
Gilles Sansig, Klaus Klebs, Markus Schmutz, Wolfgang Froestl, Herman van 
der Putten, Johannes Mosbacher, Hans Brauner-Osborne, Peter Waldmeier, 
Bernhard Bettler 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2722 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03013.x 

------------------------------------------------------------------------ 
Microglial activation with atypical proinflammatory cytokine expression 
in a rat model of Parkinson's disease 

Amaicha M. Depino, Chris Earl, Elke Kaczmarczyk, Carina Ferrari, Hugo 
Besedovsky, Adriana del Rey, Fernando J. Pitossi, Wolfgang H. Oertel 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2731 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03014.x 

------------------------------------------------------------------------ 
Depression of mGluR-mediated IPSCs by 5-HT in dopamine neurons of the 
rat substantia nigra pars compacta 

E. Paolucci, N. Berretta, A. Tozzi, G. Bernardi, N. B. Mercuri 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2743 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03015.x 

------------------------------------------------------------------------ 
Inhibitory effect of mouse neocortex layer I on the underlying cellular 
network 

Dan Shlosberg, Saundra L. Patrick, Yossi Buskila, Yael Amitai 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2751 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03016.x 

------------------------------------------------------------------------ 
Oestrogen regulates sympathetic neurite outgrowth by modulating brain 
derived neurotrophic factor synthesis and release by the rodent uterus 

D. Krizsan-Agbas, T. Pedchenko, W. Hasan, P. G. Smith 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2760 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03029.x 

------------------------------------------------------------------------ 
Seizures preferentially stimulate proliferation of radial glia-like 
astrocytes in the adult dentate gyrus: functional and immunocytochemical 
analysis 

Kerstin Huttmann, Matthew Sadgrove, Anke Wallraff, Stefan Hinterkeuser, 
Frank Kirchhoff, Christian Steinhauser, William P. Gray 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2769 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03002.x 

------------------------------------------------------------------------ 
Synaptic and non-synaptic mechanisms of amygdala recruitment into 
temporolimbic epileptiform activities 

Julia Klueva, Thomas Munsch, Doris Albrecht, Hans-Christian Pape 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2779 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.02984.x 

------------------------------------------------------------------------ 
Correlated stage- and subfield-associated hippocampal gene expression 
patterns in experimental and human temporal lobe epilepsy 

Albert J. Becker, Jian Chen, Alexander Zien, Dmitry Sochivko, Sabine 
Normann, Johannes Schramm, Christian E. Elger, Otmar D. Wiestler, Ingmar 
Blumcke 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2792 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.02993.x 

------------------------------------------------------------------------ 
VEGF is necessary for exercise-induced adult hippocampal neurogenesis 

Klaus Fabel, Konstanze Fabel, Betty Tam, Daniela Kaufer, Armin Baiker, 
Natalie Simmons, Calvin J. Kuo, Theo D. Palmer 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2803 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03041.x 

------------------------------------------------------------------------ 
Gradient of adaptability in four different motor systems performing the 
same learned motor task in cats 

Agnes Gruart, Michael Streppel, Orlando Guntinas-Lichius, Doychin N. 
Angelov, Wolfram F. Neiss, Jose M. Delgado-Garcia 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2813 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03019.x 

------------------------------------------------------------------------ 
Context-specific acquisition of location discrimination by hippocampal 
place cells 

Robin M. A. Hayman, Subhojit Chakraborty, Michael I. Anderson, Kathryn 
J. Jeffery 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2825 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03035.x 

------------------------------------------------------------------------ 
Hippocampal gene expression profiles in passive avoidance conditioning 

Velia D'Agata, Sebastiano Cavallaro 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2835 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03025.x 

------------------------------------------------------------------------ 
Enrichment enhances the expression of sgk, a glucocorticoid-induced 
gene, and facilitates spatial learning through glutamate AMPA receptor 
mediation 

Eminy H. Y. Lee, W. L. Hsu, Y. L. Ma, P. J. Lee, C. C. Chao 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2842 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03032.x 

------------------------------------------------------------------------ 
Ear of stimulation determines schizophrenia-normal brain activity 
differences in an auditory paired-stimuli paradigm 

Brett A. Clementz, Jacqueline R. Dzau, Laura D. Blumenfeld, Scott 
Matthews, Johanna Kissler 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2853 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03027.x 

------------------------------------------------------------------------ 
Pain processing within the primary somatosensory cortex in humans 

Koji Inui, Xiaohong Wang, Yunhai Qiu, Binh Thi Nguyen, Shiro Ojima, 
Yohei Tamura, Hiroki Nakata, Toshiaki Wasaka, Tuan Diep Tran, Ryusuke 
Kakigi 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2859 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.02995.x 

------------------------------------------------------------------------ 
Engagement of visual fixation suppresses sensory responsiveness and 
multisensory integration in the primate superior colliculus 

A. H. Bell, B. D. Corneil, D. P. Munoz, M. A. Meredith 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2867 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.02976.x 

------------------------------------------------------------------------ 
Mechanisms of time-based figure-ground segregation 

Farid I. Kandil, Manfred Fahle 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2874 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03022.x 

------------------------------------------------------------------------ 
Sensorimotor memory and grip force control: does grip force anticipate a 
self-produced weight change when drinking with a straw from a cup? 

Dennis A. Nowak, Joachim Hermsdorfer 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2883 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03011.x 

------------------------------------------------------------------------ 
Short Communications 
------------------------------------------------------------------------ 
Chemokine modulation of high-conductance Ca2+-sensitive K+ currents in 
microglia from human hippocampi 

A. Bordey, D. D. Spencer 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2893 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03021.x 

------------------------------------------------------------------------ 
Non-calyceal excitatory inputs mediate low fidelity synaptic 
transmission in rat auditory brainstem slices 

Martine Hamann, Brian Billups, Ian D. Forsythe 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2899 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03017.x 

------------------------------------------------------------------------ 
Maternal care influences neuronal survival in the hippocampus of the rat 

Timothy W. Bredy, Rebecca J. Grant, Danielle L. Champagne, Michael J. 
Meaney 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2903 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.02965.x 

------------------------------------------------------------------------ 
Tracking mouse visual pathways with WGA transgene 

Yoko Hanno, Masakiyo Nakahira, Kou-ichi Jishage, Tetsuo Noda, Yoshihiro 
Yoshihara 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2910 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03023.x 

------------------------------------------------------------------------ 
Delay-period activities in two subdivisions of monkey inferotemporal 
cortex during pair association memory task 

Yuji Naya, Masatoshi Yoshida, Masaki Takeda, Ryoko Fujimichi, Yasushi 
Miyashita 
European Journal of Neuroscience; Volume 18, Issue 10, Page 2915 

http://www.blackwell-synergy.com/links/doi/10.1111/j.1460-9568.2003.03020.x 

------------------------------------------------------------------------ 


Vera Heinemann
FENS Office Berlin
Max-Delbrueck-Center for Molecular Medicine (MDC)
Robert-Roessle-Str. 10
D-13092 Berlin
Phone: +49 30 9406 3336
Fax: +49 30 9406 3819
e-mail: v.heinemann@mdc-berlin.de


