From d.h.koopmans@med.rug.nl Tue Nov 18 12:15:17 2003
Return-Path: <d.h.koopmans@med.rug.nl>
Received: from medmail.med.rug.nl (medmail.med.rug.nl [129.125.135.2])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAIAGcOj018877
	for <m.bulacu@ai.rug.nl>; Tue, 18 Nov 2003 11:16:38 +0100
Received: from mail.med.rug.nl (mail.med.rug.nl [129.125.159.6])
	by medmail.med.rug.nl (8.9.3p3/8.9.3) with ESMTP id LAA06490;
	Tue, 18 Nov 2003 11:15:19 +0100 (MET)
Message-Id: <200311181015.LAA06490@medmail.med.rug.nl>
Received: from MEDMAILMW1/SpoolDir by mail.med.rug.nl (Mercury 1.48);
    18 Nov 03 11:15:20 GMT+0100
Received: from SpoolDir by MEDMAILMW1 (Mercury 1.48); 18 Nov 03 11:15:18 GMT+0100
From: "D.H.KOOPMANS" <d.h.koopmans@med.rug.nl>
Organization: faculty of medical sciences (RuG)
To: "promovendi"<d.h.koopmans@med.rug.nl>
Date: Tue, 18 Nov 2003 11:15:17 GMT+0100
MIME-Version: 1.0
Content-type: text/plain;
  charset=US-ASCII
Content-transfer-encoding: 7BIT
Subject: Activity Sunday afternoon 23 November
X-Confirm-Reading-To: "D.H.KOOPMANS" <d.h.koopmans@med.rug.nl>
X-pmrqc: 1
Priority: normal
In-reply-to: <200311180958.KAA05675@medmail.med.rug.nl>
X-mailer: Pegasus Mail for Win32 (v3.12)
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=2.2, required 4,
	FROM_AND_TO_SAME_5 1.31, INVALID_DATE 1.52, IN_REP_TO -0.85,
	MSG_ID_ADDED_BY_MTA_2 0.11, NOSPAM_INC -0.21, OFFER 0.20,
	SPAM_PHRASE_03_05 1.08, SUBJECT_MONTH -0.48, SUBJECT_MONTH_2 -0.48)
X-ai-MailScanner-SpamScore: ss
Status: R 
X-Status: N
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

Dear students,

After having a delicious Italian dinner yesterday, next Sunday will be
even better!! On Sunday the 23rd of November we organize a Royal
Sunday from 16h00 till 19h00, preceeded by a visit to the Groninger
museum from 13h00 till 15h00. 

Who wants to go to the Groninger museum can sign up this week 
at the
International Service Desk in the Academy Building for only 6 Euro.
There will be a guided tour in English from 13h30 till 14h30. (you
won't get this by yourself), and it's nice to go there with a group of
foreign students. The university will pay the guided tour (of 4 euro),
so make use of this special offer! You can sign up till Friday 16h00.

After this you can go to the GSp-house, where the Royal Afternoon
starts around 16h00. (You'll be able to drink a cup of coffee or tea
at 15h00.) There's a small entrance fee of only 1 euro to pay for the
Dutch snacks and cookies. It's important that you realise that you
don't have to go to the museum to visit the Royal Afternoon. And of
course you can also choose to visit only the museum. 
Nevertheless,
there are three activities that make this afternoon worth visiting.
  a.. Doeko Bosscher, the former rector of the University of 
Groningen   (a really sympathetic man!) will tell you everything about: The
  Royal House and the Royals in the Netherlands." Who is the 
queen,   where does Maxima come from and when will the child of
  Willem-Alexander (Crown-prins) and Maxima be born? If you live in
  the Netherlands you will want to know about Dutch culture (right?),
  so you have to know about the royals! b.. You can have a taste of
  'Oranjekoek', it's some sort of pie that is very tasteful and is
  very Dutch. The royal family's surname is 'van Oranje'(Orange),
  that's why this cake is eaten at special occasions. And of course 
we  will have the famous 'stroopwafels', a Dutch wonderfull wafel with
  sirop. c.. After the lecture from Prof. dr. Bosscher there will be a
  quiz about the Royal Family, to check if you payed attention! Or
  maybe you already know a lot about the Royal Family?? The 
prize will   be something tasteful & orange!
Hope to see you all coming sunday...first in the Groninger museum 
and later on at our Royal Afternoon at the GSp-house (Kraneweg 33). 


Wytse van der Kolk & Colette Kraaijenhagen
on behalf of WINGS-ESN and ISD.


