From L.Schomaker@ai.rug.nl Mon Dec  1 09:49:31 2003
Return-Path: <L.Schomaker@ai.rug.nl>
Received: from ai.rug.nl (psyX7.ai.rug.nl [129.125.139.207])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hB18nVOj023371
	for <bulacu@ai.rug.nl>; Mon, 1 Dec 2003 09:49:31 +0100
Message-ID: <3FCB009B.9070707@ai.rug.nl>
Date: Mon, 01 Dec 2003 09:49:31 +0100
From: Lambert Schomaker <L.Schomaker@ai.rug.nl>
User-Agent: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.2.1) Gecko/20030225
X-Accept-Language: en-us, en
MIME-Version: 1.0
To: bulacu@ai.rug.nl
Subject: [Fwd: Query regarding Automatic Writer  Identification using CO3's]
Content-Type: multipart/mixed;
  boundary="------------080304090001010702090009"
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam (whitelisted),
	SpamAssassin (score=-100.7, required 4, DEAR_SOMEBODY 0.10,
	FWD_MSG -0.56, SPAM_PHRASE_03_05 1.08, USER_AGENT -0.52,
	USER_AGENT_MOZILLA_UA -0.60, USER_IN_WHITELIST -100.00,
	X_ACCEPT_LANG -0.21)
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

This is a multi-part message in MIME format.
--------------080304090001010702090009
Content-Type: text/plain; charset=us-ascii; format=flowed
Content-Transfer-Encoding: 7bit

don't react

--------------080304090001010702090009
Content-Type: message/rfc822;
 name="Query regarding Automatic Writer  Identification using CO3's"
Content-Transfer-Encoding: 7bit
Content-Disposition: inline;
 filename="Query regarding Automatic Writer  Identification using CO3's"

From rvpatkar@buffalo.edu  Mon Dec  1 03:41:47 2003
Return-Path: <rvpatkar@buffalo.edu>
Received: from localhost (localhost.localdomain [127.0.0.1])
	by psyx7.ai.rug.nl (8.12.8/8.12.8) with ESMTP id hB12fk1N002833
	for <lambert@localhost>; Mon, 1 Dec 2003 03:41:47 +0100
Received: from tcw2.ai.rug.nl [129.125.139.237]
	by localhost with POP3 (fetchmail-6.2.0)
	for lambert@localhost (single-drop); Mon, 01 Dec 2003 03:41:47 +0100 (CET)
Received: from mail4.acsu.buffalo.edu (mail4.acsu.buffalo.edu [128.205.6.83])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with SMTP id hB12ewOj013186
	for <schomaker@ai.rug.nl>; Mon, 1 Dec 2003 03:40:58 +0100
Received: (qmail 7573 invoked by uid 60001); 1 Dec 2003 02:40:56 -0000
To: schomaker@ai.rug.nl
Subject: Query regarding Automatic Writer  Identification using CO3's
Date: Sun, 30 Nov 2003 21:40:56 -0500
From: rvpatkar@buffalo.edu
Message-ID: <1070246456.3fcaaa38aec52@mail4.buffalo.edu>
X-Mailer: University at Buffalo WebMail Cyrusoft SilkyMail v1.1.10 24-January-2003
MIME-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 8bit
X-Originating-IP: 128.205.35.2
X-Originator-Info: login-id=rvpatkar, server=buffalo.edu
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=2.5, required 4,
	DEAR_SOMEBODY 0.10, NO_REAL_NAME 1.28, SPAM_PHRASE_03_05 1.08)
X-ai-MailScanner-SpamScore: ss

Dear Dr. Schomaker, 

I am a Graduate student in Computer Science at University at Buffalo. I
have been working under Dr. Sargur Srihari (CEDAR, SUNY Buffalo) at
handwriting recognition. I recently came across the paper "Automatic
Writer  Identification Using Connected-Component Contours and Edge-Based
Features of Upper-Case Western Script", by your goodselves and Marius
Bulacu.and had a query about it. 

Could you kindly let me know whether there was some significant reason
for the use of Kohonen's Self Organising Feature Maps for generating the
codebook of connected component contours, because by the look of it,
computing CO3's for any alphabet set seems to be quite a time intensive
job. However, your results are very encouraging. Hence the urge to also
know whether you used some tweaking and tunings?

Kindly do oblige.

Thanking you for your time,

Regards,

Rohit Patkar


--------------080304090001010702090009--


