From conference@inmeet.com Thu Oct 16 10:18:05 2003
Return-Path: <conference@inmeet.com>
Received: from c011.snv.cp.net (h001.c011.snv.cp.net [209.228.34.214])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with SMTP id h9G8IfqR032503
	for <m.bulacu@ai.rug.nl>; Thu, 16 Oct 2003 10:18:42 +0200
Received: (cpmta 1968 invoked from network); 16 Oct 2003 01:18:38 -0700
Received: from 202.83.106.20 (HELO ims04)
  by smtp.inmeet.com (209.228.34.214) with SMTP; 16 Oct 2003 01:18:38 -0700
X-Sent: 16 Oct 2003 08:18:38 GMT
Message-ID: <022101c393be$0c4f2a90$0400a8c0@ims04>
From: "Conference" <conference@inmeet.com>
To: <Undisclosed-Recipient:;>
Subject: International Conference on Image Processing 2004
Date: Thu, 16 Oct 2003 16:18:05 +0800
MIME-Version: 1.0
Content-Type: text/plain;
  charset="iso-8859-1"
Content-Transfer-Encoding: 7bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2800.1158
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2800.1165
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=2.8, required 4,
	MAILTO_TO_SPAM_ADDR 0.69, OUTLOOK_UNDISC_RECIPS 0.47,
	SPAM_PHRASE_00_01 0.78, TO_MALFORMED 0.59, USER_AGENT_OE 0.18)
X-ai-MailScanner-SpamScore: ss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

Call for Papers - ICIP 2004

   ICIP 2004  Organizing  Committee  would  like  to  invite   you  to
   participate  in  the Eleventh  International  Conference  on  Image
   Processing,  which will be  held in Suntec  Singapore International
   Convention & Exhibition Centre, Singapore, from October 24-27, 2004.
   We enclose the ICIP2004 Call for Papers.
   We  are  looking forward to  receiving  your contributions,  and to
   meeting you in the garden city of Singapore.

       ICIP 2004 Organizing Committee



=====================================================================
                            ICIP2004
                        CALL FOR PAPERS
                              and
             CALL FOR SPECIAL SESSIONS AND TUTORIALS

                    <http://www.icip2004.org/>

                 IEEE Signal Processing Society
           International Conference on Image Processing
                     October 24-27, 2004
               Suntec Singapore International
               Convention & Exhibition Centre
                          Singapore
=====================================================================


CONFERENCE FOCUS
================

   The International Conference on  Image Processing (ICIP), sponsored
   by the IEEE Signal Processing Society, is the premier forum for the
   presentation of technological advances and  research results in the
   fields of theoretical,  experimental,  and applied image and  video
   processing. ICIP-2004,the eleventh in the series that has been held
   annually since  1994,  will bring   together leading engineers  and
   scientists in image   processing from around  the  world.  Research
   frontiers in  fields ranging    from traditional  image  processing
   applications  to  evolving  multimedia and   video technologies are
   regularly advanced by   results  first reported in   ICIP technical
   sessions.


TOPICS OF INTERESTS
===================

1. IMAGE/VIDEO CODING AND  TRANSMISSION:
   Still  image  and video coding,  model-based  and synthetic-natural
   hybrid coding,  source/channel coding, stereoscopic and 3-D coding,
   coding standards, image and video  over networks, error resilience,
   video streaming.

2. IMAGE/VIDEO PROCESSING AND ANALYSIS:
   Linear  and nonlinear  filtering   and  enhancement,   restoration,
   multiframe     image   restoration,   segmentation,    wavelets and
   multiresolution processing,  morphological  processing,   color and
   multispectral   processing,   stereoscopic  and   3-D   processing,
   modeling, analysis,    interpolation and  spatial  transformations,
   motion detection  and estimation, image  sequence processing, noise
   modeling, architectures and  software, neural,  adaptive, and fuzzy
   processing, computer vision.

3. IMAGE FORMATION:
   Acoustic, radar,  and  tomographic  imaging,  nuclear,  X-ray,  and
   magnetic resonance imaging, geophysical  and seismic imaging, radio
   astronomy    and    speckle    imaging,    optical    imaging,  and
   synthetic-natural hybrid image systems.

4. IMAGE SCANNING, PRINTING, DISPLAY AND COLOR:
   Scanning   and   sampling,   quantization   and halftoning,   color
   reproduction,  image representation   and   rendering, display  and
   printing systems, image quality assessment.

5. IMAGE/VIDEO STORAGE, RETRIEVAL, AND MULTIMEDIA:
   Image and video databases, image search and sorting, video indexing
   and  editing,  integration of images  and  video with  other media,
   content-based multimedia,  multimedia  applications, authentication
   and watermarking.

6. APPLICATIONS:
   Application of image  processing technology to any field, including
   biomedical    sciences,    astronomy,    geosciences,  environment,
   humanities, arts, forensic sciences, and document processing.


PAPER SUBMISSION
================

   Prospective authors are invited to submit extended summaries of not
   more than     four  (4) pages     including results,  figures   and
   references.  Papers will be accepted  only by electronic submission
   through the conference web site:

                       <http://www.icip2004.org/>

   Submission of extended summary      : January 10, 2004
   Notification of acceptance          : April 10, 2004
   Submission of camera-ready papers   : May 10, 2004


TUTORIALS AND SPECIAL SESSIONS PROPOSALS
========================================
   Tutorials  will  be held on  Sunday,   October 24, 2004.  Proposals
   for tutorials must include a title,  an outline of the tutorial and
   its motivation, contact information for the  presenter, and a short
   description of the material to  be covered. Proposals for tutorials
   should  be  submitted  to  Prof. Ashraf Kassim  (ashraf@nus.edu.sg
<mailto:ashraf@nus.edu.sg>)
   before December 10, 2003.

   ICIP-2004  will  include  a  number  of  special sessions.  Special
   sessions  proposals  should be submitted to Special Sessions Chair.
   Proposals  for  special sessions  must include  a title, rationale,
   session outline, contact information for the session chair(s), and
   a list of authors who have agreed to present papers in the session.
   Proposals  for  special  sessions  should  be  submitted  to  Prof.
   Chin-Hui Lee (chl@ece.gatech.edu <mailto:chl@ece.gatech.edu>) before
December 10, 2003.


CONFERENCE COMMITTEE
====================
General Co-Chair
   Meng-Hwa ER (emher@ntu.edu.sg <mailto:emher@ntu.edu.sg>)
   Nanyang Technological University, Singapore

   Alex KOT (eackot@ntu.edu.sg <mailto:eackot@ntu.edu.sg>)
   Nanyang Technological University, Singapore

Technical Program
   Robert GRAY (rmgray@stanford.edu <mailto:gray@ee.stanford.edu>)
   Stanford University, USA

   Kai-Kuang MA (ekkma@ntu.edu.sg <mailto:ekkma@ntu.edu.sg>)
   Nanyang Technological University, Singapore

Special Sessions
   Chin-Hui LEE (chl@ece.gatech.edu <mailto:chl@ece.gatech.edu>)
   Georgia Institute of Technology, USA

Tutorials
   Ashraf KASSIM (ashraf@nus.edu.sg <mailto:ashraf@nus.edu.sg>)
   National University of Singapore, Singapore

Publications
   Charles Graham LEEDHAM (asgleedham@ntu.edu.sg
<mailto:asgleedham@ntu.edu.sg>)
   Nanyang Technological University, Singapore

Finance
   Yap-Peng TAN (eyptan@ntu.edu.sg <mailto:eyptan@ntu.edu.sg>)
   Nanyang Technological University, Singapore

Registration & Local Arrangements
   Yong-Kim CHONG (eykchong@ntu.edu.sg <mailto:eykchong@ntu.edu.sg>)
   Nanyang Technological University, Singapore

Exhibits
   Ping XUE (epxue@ntu.edu.sg <mailto:epxue@ntu.edu.sg>)
   Nanyang Technological University, Singapore

   Susanto RAHARDJA (rsusanto@i2r.a-star.edu.sg
<mailto:rsusanto@i2r.a-star.edu.sg>)
   Institute for Infocomm Research, Singapore

Publicity
   Lap-Pui CHAU (elpchau@ntu.edu.sg <mailto:elpchau@ntu.edu.sg>)
   Nanyang Technological University, Singapore

Social Program
   Say-Wei FOO (eswfoo@ntu.edu.sg <mailto:eswfoo@ntu.edu.sg>)
   Nanyang Technological University, Singapore

Web
   Kap-Luk CHAN (eklchan@ntu.edu.sg <mailto:eklchan@ntu.edu.sg>)
   Nanyang Technological University, Singapore

North American Liaison
   Thrasyvoulos N. PAPPAS (pappas@ece.northwestern.edu
<mailto:pappas@ece.northwestern.edu>)
   Northwestern University, USA

European Liaison
   Thomas SIKORA (sikora@nue.tu-berlin.de <mailto:sikora@nue.tu-berlin.de>)
   Technical University Berlin, Germany

Secretary
   Olga SOURINA (eosourina@ntu.edu.sg <mailto:eosourina@ntu.edu.sg>)
   Nanyang Technological University, Singapore

Conference Manager
   Integrated Meetings Specialist Pte Ltd
   icip2004@icip2004.org <mailto:icip2004@icip2004.org>

===================================================================




