From ezaki@toba-cmt.ac.jp Thu Nov 27 08:29:56 2003
Return-Path: <ezaki@toba-cmt.ac.jp>
Received: from twing.toba-cmt.ac.jp (twing.toba-cmt.ac.jp [202.26.248.3])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with SMTP id hARFUIOj008426
	for <M.Bulacu@ai.rug.nl>; Thu, 27 Nov 2003 16:30:20 +0100
Received: (qmail 14347 invoked from network); 27 Nov 2003 15:30:06 -0000
Received: from tcwx1.ai.rug.nl (HELO twing.toba-cmt.ac.jp) (129.125.139.246)
  by twing.toba-cmt.ac.jp with SMTP; 27 Nov 2003 15:30:06 -0000
Message-Id: <200311270729.AA02040@twing.toba-cmt.ac.jp>
From: Nobuo Ezaki <ezaki@toba-cmt.ac.jp>
Date: Thu, 27 Nov 2003 16:29:56 +0900
To: M.Bulacu@ai.rug.nl
Subject: Result
MIME-Version: 1.0
X-Mailer: AL-Mail32 Version 1.13
Content-Type: text/plain;
  charset=us-ascii
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=1.2, required 4,
	DATE_IN_PAST_06_12 0.45, SPAM_PHRASE_00_01 0.78)
X-ai-MailScanner-SpamScore: s
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

Hi

 This is my result. Especially, ryoungt_13.08.2002 is not good.
 But Train sample is good.


Text Detection using edge feature						

Results :						

Dir	No. images	Precision	Recall	Average		
ryoungt_05.08.2002	113	50.8%	68.8%	59.8%		Original size
ryoungt_13.08.2002	134	40.9%	55.7%	48.3%		Original size
sml_01.08.2002		4	95.2%	67.8%	81.5%		Original size
all				46.2%	61.8%	54.0%		
				
Dir	No. images	Precision	Recall	Average		
appanar_06.08.2002	34	49.5%	43.5%	46.5%		640*480
lfsosa_12.08.2002	174	68.3%	60.3%	64.3%		640*480
ryouungt_03.09.2002	25	26.3%	51.1%	38.7%		640*480
ryoungt_05.08.2002	20	60.7%	70.5%	65.6%		640*480
all				61.0%	62.7%	64.4%		

--
Nobuo EZAKI  Kunstmatige Intelligentie  RuG
mailto : ezaki@toba-cmt.ac.jp or N.Ezaki@ai.rug.nl
http://www.info.toba-cmt.ac.jp/~ezaki/
tel : +31-50-363-6955     fax : +31-50-363-6687


