From the-institute@ieee.org Fri Oct 24 00:52:24 2003
Return-Path: <owner-the-institute@boldfish.ieee.org>
Received: from boldfish (boldfish.ieee.org [140.98.194.25])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id h9OAsjqR010303
	for <m.bulacu@ai.rug.nl>; Fri, 24 Oct 2003 12:54:46 +0200
Received: from boldfish.ieee.org (boldfish [140.98.194.25])
	by boldfish (8.9.3+Sun/8.9.3) with ESMTP id GAA15528
	for <m.bulacu@ai.rug.nl>; Fri, 24 Oct 2003 06:54:43 -0400 (EDT)
Date: Thu, 23 Oct 2003 18:52:24 EDT
Message-Id: <A10669495448855582700@boldfish.ieee.org>
From: the-institute@ieee.org (IEEE - The Institute Editors)
Sender: owner-the-institute@boldfish.ieee.org
Mime-Version: 1.0
X-Sender: owner-the-institute@boldfish.ieee.org
X-Sender: the-institute@ieee.org (IEEE - The Institute Editors)
X-List-Software: "BoldFish Version 2.3.2.2/010905.1" <http://www.boldfish.com>
Subject: The Institute Online Alert for 23 October 2003
To: m.bulacu@ai.rug.nl
References: <A10669495451132320585.m.bulacu@ai.rug.nl>
Received: from 140.98.194.25 by 140.98.194.25
	with EWP id A10669495451135052091
	for <m.bulacu@ai.rug.nl>; Thu, 23 Oct 2003 18:52:25 EDT
List-Unsubscribe: http://boldfish.ieee.org:8080/unsub/the-institute/m.bulacu%40ai.rug.nl/f1e5c7e51ed3292cce39abe9892f3655/
Content-Type: text/plain;
  charset="us-ascii"
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=1.1, required 4,
	FORGED_RCVD_FOUND 0.77, FREE_ACCESS 0.61, MEMBER 0.21,
	MSG_ID_ADDED_BY_MTA_2 0.11, REFERENCES -0.52, SPAM_PHRASE_03_05 1.08,
	SUBJECT_MONTH -0.48, SUBJECT_MONTH_2 -0.48,
	SUSPECT_LIST_HEADERS -0.20)
X-ai-MailScanner-SpamScore: s
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  


Dear MARIUS BULACU: 


Here's your report on news around the IEEE, from the editors of 
The Institute. The most current version of The Institute can always be 
found at <http://www.ieee.org/theinstitute>

________________________________________________________
IN THIS ISSUE:

1. IEEE Network Magazine Tops Annual Citation Rankings
2. Respond to the IEEE-USA Salary Survey and Get Free Access to Data
3. Election Ballots Due 3 November
4. Renew Your 2004 Membership Online
5. Needed: Student Teams to Solve Real-World Problems
6. IEEE Members Receive Discount to Electronics Trade Show
7. Virtual Community for Volunteers Proves a Valuable Tool
8. Evaluators Wanted to Review Engineering Education Programs

Subscription information is found at the end of the newsletter.
________________________________________________________
SPONSOR'S MESSAGE:

Data Translation
"NEW" Real-Time DSP Data Acquisition.
World's Most Accurate and Noise-Free

<http://www.datatranslation.com/real-time>
_______________________________________________________

A word about the links in this e-mail:
Because the URLs are long, some e-mail programs might not
capture an entire URL for direct clicking. Note that the complete link,
contained between the < > symbols, should be selected when clicking 
or copying and pasting into a browser window. Starting this fall, shorter 
URLs should prevail. 


1. IEEE Network Magazine Tops Annual Citation Rankings
For the second year in a row, IEEE Network magazine topped the list of 
telecommunications journals that other scientific publications cite most 
often, according to the Institute for Scientific Information's (ISI's) "2002 
Journal Citation Reports -- Science Edition." The bimonthly magazine for 
the first time also captured the top spot for citations in two other journal 
categories: electrical and electronics engineering, and computer science 
information systems. 
Read about how other IEEE publications are ranked at
<http://www.theinstitute.ieee.org/inst_art.jsp?isno=10031&arnumber=10031_10w.newscitationrpt&section=5>


2. Respond to the IEEE-USA Salary Survey and Get Free Access to Data
Ever wonder how your salary compares to others with a similar technical 
background? If so, IEEE-USA is offering U.S. members who take its 
Salary and Fringe Benefit Survey free annual access to its new Salary 
Service. Responses to the survey will help IEEE-USA build a 2004 salary 
comparison system for electrotechnology professionals. Read more at
<http://www.theinstitute.ieee.org/inst_art.jsp?isno=10031&arnumber=10031_10w.prodsalarysurv&section=11>


3. Election Ballots Due 3 November
The IEEE Annual Election ballots for this year's election have been 
mailed to the voting membership. Be sure to cast your votes and return 
your signed ballot. The deadline for receipt of all ballots is noon on 3 
November 2003. If you no longer have the postage-paid envelope 
provided in your election packet, you may mail your signed ballot to 
Survey and Ballot Systems Inc., Box 46430, Eden Prairie, MN, USA 
55344-6430. Contact Angela Wyckoff at +1 732 562 3932 or via e-mail at 
<a.wyckoff@ieee.org> with any questions or visit 
<http://www.ieee.org/organizations/corporate/candidates.htm>


4. Renew Your 2004 Membership Online
Paper renewal notices are in the mail, and the 2004 Web Renewal site is 
now open at <http://www.ieee.org/renewal>. The online renewal process 
is faster and members could find it more convenient, and it helps to 
reduce the IEEE's processing costs. Find out more at
<http://www.theinstitute.ieee.org/inst_art.jsp?isno=10031&arnumber=10031_10w.newsrenewal&section=5>

________________________________________________________
SPONSOR'S NOTICE from The MathWorks:

HELP US LEARN! If your work involves technical computing, signal 
processing, control design, data analysis or embedded programming, 
we'd like you to take our short online survey about the software tools 
available for these uses. Click on this link between October 22 and 
November 5 to take the survey.

<http://survey2.greenfieldonline.com/wi/p7347160/i.asp>
________________________________________________________


5. Needed: Student Teams to Solve Real-World Problems
If you can dream up a device to help make the world safer, your team 
could win US$15 000. Teams of university students throughout the world 
are invited to participate in the 2004 IEEE Computer Society International 
Design Competition, an annual challenge in which teams of 
undergraduate engineering students design -- from inception to prototype 
-- a special-purpose, computer-based device that solves a real-world 
problem. Proposals are due by 1 November. More details are at
<http://www.theinstitute.ieee.org/inst_art.jsp?isno=10031&arnumber=10031_10w.deadlinecsidc&section=41>


6. IEEE Members Receive Discount to Electronics Trade Show
Register by 8 November to receive a US$300 discount on admission to 
Comdex, a leading electronics trade show, to be held 17 to 20 November 
in Las Vegas, Nev., USA. For more information and to register, go to
<http://ad.doubleclick.net/clk;6359941;8488907;g?http://www.comdex.com/lasvegas2003/register/>


7. Virtual Community for Volunteers Proves Valuable Tool
To say that keeping the more than 1800 IEEE Sections, Chapters, and 
Affinity Groups around the world connected is a challenge is an 
understatement. A new tool on the Internet from IEEE Regional Activities 
keeps conversations and information flowing. To learn more, visit 
<http://www.theinstitute.ieee.org/inst_art.jsp?isno=10031&arnumber=10031_10w.featurecommnew&section=4>


8. Evaluators Wanted to Review Engineering Education Programs
The IEEE Educational Activities Board is seeking professionals -- especially from industry and government -- to serve as evaluators of undergraduate engineering programs in the United States. 
The evaluations help ensure that future generations of engineers will receive a quality education. Deadline for receipt of completed applications is 15 November. Read more at
<http://www.theinstitute.ieee.org/inst_art.jsp?isno=10031&arnumber=10031_10w.deadlineabet&section=2>


*****************************************************************
Manage Your Subscription to The Institute Online Alert: 	
The Institute Online Alert is prepared twice a month by the editors of The 
Institute, the news source for members of the Institute of Electrical and 
Electronics Engineers. You'll find The Institute's home page at: 
<http://www.ieee.org/theinstitute>

Members of the IEEE who have provided an e-mail address are 
automatically subscribed to the Alert as a member benefit. 

Those members who wish to OPT-OUT of the Alert may do so by going
to: <http://www.ieee.org/io-enotice>

Fill out the form with your e-mail address and member number. For 
convenience, your member number is provided here: MEMBER NO. 

Those members who need to CHANGE CONTACT INFO on file with the
IEEE, including e-mail addresses, should do so at:
<http://www.ieee.org/membership/coa.xml>

Those members who need to UPDATE THEIR IEEE EMAIL ALIAS, may
do so by going to: <http://eleccomm.ieee.org>

Or, if you need assistance with your membership, you may contact IEEE
Member Services by e-mail at <mailto:member-services@ieee.org> 
or by telephone +1 800 678 IEEE (+1 800 678 4333) from within the U.S. 
or +1 732 981 0060 outside the U.S. or fax +1 732 562 5445. 

If this e-mail was forwarded to you and you are not an IEEE member, 
you may SUBSCRIBE to the Alert (and manage your subscription by 
changing e-mail addresses or unsubscribing) at: 
<http://www.ieee.org/theinstitute/signup.html>

If you have questions or comments about The Institute Online Alert, 
please send a message to: <mailto:tialert@ieee.org>
__________________________________________________________
Copyright 2003 The Institute of Electrical and Electronics Engineers, Inc.



