From m.i.bulacu@phys.rug.nl Thu Oct 23 11:11:42 2003
Return-Path: <m.i.bulacu@phys.rug.nl>
Received: from babylon.nature.com (babylon.nature.com [216.35.73.243])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with SMTP id h9N8BiqR012309
	for <m.bulacu@ai.rug.nl>; Thu, 23 Oct 2003 10:11:44 +0200
Message-Id: <200310230811.h9N8BiqR012309@tcw2.ppsw.rug.nl>
Subject: Nature article: Magnetic pioneers net Nobel for putting medicine in the picture
Date: Thu, 23 Oct 2003 04:11:42 -0500
From: m.i.bulacu@phys.rug.nl
To: m.bulacu@ai.rug.nl
CC: 
Mime-Version: 1.0
Content-Type: text/plain;
  charset="iso-8859-1"
X-Mailer: Tango 2000 Version 4.05.020
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=3.1, required 4,
	MIME_EXCESSIVE_QP 0.98, NO_REAL_NAME 1.28, SPAM_PHRASE_00_01 0.78)
X-ai-MailScanner-SpamScore: sss
Content-Transfer-Encoding: 8bit
X-MIME-Autoconverted: from quoted-printable to 8bit by tcw2.ppsw.rug.nl id h9N8BiqR012309
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  



Your friend or colleague m.i.bulacu@phys.rug.nl thought this article from Nature
would be of particular interest to you. Their message is below.
					
Nature article: Magnetic pioneers net Nobel for putting medicine in the picture
					
The address is:
http://www.nature.com/cgi-taf/DynaPage.taf?file=/nature/journal/v425/n6958/full/425547a_fs.html
					
Their message:
despre Nobel MRI

Nature (www.nature.com)

To view the whole range of information available in Nature and its portals, visit 
www.nature.com/nature

To subscribe to the science journal with the most cutting-edge research, news, 
views and reviews, click www.nature.com/subscribe.




