From v.heinemann@mdc-berlin.de Wed Nov  5 15:02:59 2003
Return-Path: <v.heinemann@mdc-berlin.de>
Received: from server1.bbb2.mdc-berlin.de (server1.bbb2.mdc-berlin.de [141.80.34.10])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hA5E2xHC006058
	for <m.bulacu@ai.rug.nl>; Wed, 5 Nov 2003 15:02:59 +0100
Received: from vheine ([141.80.161.92])
	by server1.bbb2.mdc-berlin.de (8.12.10/8.12.10) with SMTP id hA5E2xeN026069
	for <m.bulacu@ai.rug.nl>; Wed, 5 Nov 2003 15:02:59 +0100 (MET)
Date: Wed, 5 Nov 2003 15:02:59 +0100 (MET)
Message-Id: <200311051402.hA5E2xeN026069@server1.bbb2.mdc-berlin.de>
From: FENS Office Berlin<v.heinemann@mdc-berlin.de>
To: m.bulacu@ai.rug.nl
Subject: FENS Job Market November 2003
Mime-Version: 1.0
Content-Type: text/plain;
  charset=us-ascii
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=2.4, required 4,
	DEAR_SOMEBODY 0.10, LINES_OF_YELLING 0.21, LINES_OF_YELLING_2 0.22,
	LINES_OF_YELLING_3 0.32, MEMBER_2 0.29, NORMAL_HTTP_TO_IP 1.28,
	SALE 0.21, SPAM_PHRASE_00_01 0.78, SUBJECT_MONTH -0.48,
	SUBJECT_MONTH_2 -0.48)
X-ai-MailScanner-SpamScore: ss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  



Dear Fens member,


Please find below the latest update from the FENS Job Market. Please refer 
to the FENS internet site at www.fens.org  (Job Market) for further details 
and/or for the INSTRUCTIONS how to put an ad.

Under the same internet address you may want to check the "CALENDAR"
Section as well where many CONGRESSES of interest to you are listed.
Finally, the "SERVICE" section includes several offers with reduced prices
for BOOKS and JOURNALS.
Enjoy!


-------------------------------------------------
PH.D. STUDENT POSITIONS
--------------------------------------------------


BELGIUM

No: 550
Ph.D. Student / Belgium  /  Ghent  /  Ghent University  /  Department of Experimental Psychology
Internet Address: http://141.80.163.78/outputid.asp?Code=550
===============================================

CANADA

No: 541
Ph.D. Student / Canada  /  Montreal  /  Institut National de la recherche scientifique- Institut Armand Frappier  /  Institut National de la recherche scientifique- Institut Armand Frappier
Internet Address: http://141.80.163.78/outputid.asp?Code=541
===============================================

CZECH REPUBLIC

No: 535
Ph.D. Student / Czech Republic  /  Prague  /  Charles University  /  Dept. of Neuroscience
Internet Address: http://141.80.163.78/outputid.asp?Code=535
===============================================

GERMANY

No: 567
Ph.D. Student / Germany  /  Hannover  /  Institute of Pharmacology  /  Center for Systems Neuroscience, and School of Veterinary Medicine
Internet Address: http://141.80.163.78/outputid.asp?Code=567
===============================================
No: 558
Ph.D. Student / Germany  /  Osnabrueck  /  Cognitive Science  /  Neurobiopsychology
Internet Address: http://141.80.163.78/outputid.asp?Code=558
===============================================
No: 516
Graduate Student and Post-doctoral Positions / Germany  /  Frankfurt  /  Institute for Biochemistry, Biocenter  /  currently at: Division of Biological Sciences
Internet Address: http://141.80.163.78/outputid.asp?Code=516
===============================================
No: 497
Ph.D. Student training / Germany  /  Tuebingen  /  University of Tuebingen Department of Otolaryngology  /  Tuebingen Hearing Research Centre
Internet Address: http://141.80.163.78/outputid.asp?Code=497
===============================================

NETHERLANDS

No: 573
Ph.D. Student / Netherlands  /  Amsterdam  /  Netherlands Ophthalmic Research Institute  /  Molecular Visual Plasticity
Internet Address: http://141.80.163.78/outputid.asp?Code=573
===============================================
No: 572
Ph.D. Student / Netherlands  /  Rotterdam  /  Erasmus MC, University Medical Center Rotterdam  /  Department of Neuroscience
Internet Address: http://141.80.163.78/outputid.asp?Code=572
===============================================
No: 557
Ph.D. Student / Netherlands  /  Groningen  /  BCN NeuroImaging Center - Groningen University Hospital  /  
Internet Address: http://141.80.163.78/outputid.asp?Code=557
===============================================

NEW ZEALAND

No: 521
Ph.D. Student / New Zealand  /  Auckland  /  Univ. of Auckland, Faculty of Medical and Health Sciences  /  Department of Physiology
Internet Address: http://141.80.163.78/outputid.asp?Code=521
===============================================

NORWAY

No: 570
Ph.D. Student / Norway  /  University of Oslo  /  Institute of basic medical sciences  /  Department of Anatomy
Internet Address: http://141.80.163.78/outputid.asp?Code=570
===============================================

SINGAPORE

No: 469
Ph.D. Student / Singapore  /  Singapore  /  National Neuroscience Institute  /  Epilepsy Research Lab
Internet Address: http://141.80.163.78/outputid.asp?Code=469
===============================================

SPAIN

No: 543
Ph.D. Student / Spain  /  Madrid  /  Hospital Ramon y Cajal  /  Neurobiologia-Investigacion (planta -1D)
Internet Address: http://141.80.163.78/outputid.asp?Code=543
===============================================
No: 561
Ph.D. Student / Catalonia  /  Barcelona  /  University of Barcelona  /  Department of Psychiatry and Clinical Psychobiology
Internet Address: http://141.80.163.78/outputid.asp?Code=561
===============================================

SWITZERLAND

No: 548
Ph.D. Student / Switzerland  /  Lausanne  /  Institut de Biologie cellulaire et de Morpholobie (IBCM)  /  University of lausanne, medical school
Internet Address: http://141.80.163.78/outputid.asp?Code=548
===============================================

UNITED KINGDOM

No: 554
Pre-doctoral position / UK  /  Birmingham  /  University of Birmingham  /  University Lab Physiology
Internet Address: http://141.80.163.78/outputid.asp?Code=554
===============================================

U.S.A.

No: 482
Ph.D. Student / USA  /  Milwaukee  /  University of Wisconsin  /  Psychology
Internet Address: http://141.80.163.78/outputid.asp?Code=482
===============================================



------------------------------------------------------------------
POSTDOCTORAL POSITIONS
------------------------------------------------------------------


BELGIUM

No: 337
Post-doctoral position / Belgium  /  Antwerp  /  University of Antwerp  /  Biomedical Sciences
Internet Address: http://141.80.163.78/outputid.asp?Code=337
===============================================
No: 263
Post-doctoral position / Belgium  /  Antwerp  /  University of Antwerp  /  Biomedical Sciences
Internet Address: http://141.80.163.78/outputid.asp?Code=263
===============================================

FRANCE

No: 534
Post-doctoral position / France  /  Montpellier  /  Institute des Neurosciences de Montpellier  /  INSERM U583
Internet Address: http://141.80.163.78/outputid.asp?Code=534
===============================================
No: 533
Post-doctoral position / France  /  Marseille  /  Faculty of Medicine & CNRS  /  Neurobiology
Internet Address: http://141.80.163.78/outputid.asp?Code=533
===============================================
No: 530
Post-doctoral position / France  /  Bordeaux  /  CNRS-Institut Magendie  /  CNRS
Internet Address: http://141.80.163.78/outputid.asp?Code=530
===============================================
No: 519
Post-doctoral position / France  /  CASTRES (southern France)  /  Pierre Fabre  /  DRH
Internet Address: http://141.80.163.78/outputid.asp?Code=519
===============================================
No: 518
Post-doctoral position / France  /  Marseille  /  Institut Jean Roche  /  INSERM unit 464
Internet Address: http://141.80.163.78/outputid.asp?Code=518
===============================================
No: 512
Post-doctoral position / France  /  lyon  /  centre de ginitique moliculaire et cellulaire (CGMC) UMR CNRS 5534  /  Centre de Ginitique Moliculaire et Cellulaire
Internet Address: http://141.80.163.78/outputid.asp?Code=512
===============================================
No: 510
Post-doctoral position / France  /  Orsay  /  Institut Curie  /  CNRS UMR146
Internet Address: http://141.80.163.78/outputid.asp?Code=510
===============================================
No: 509
Post-doctoral position / France  /  Marseilles  /  Faculty of Medicine and CNRS  /  UMR 6150, Integration des Informations Sensorielles
Internet Address: http://141.80.163.78/outputid.asp?Code=509
===============================================
No: 505
Post-doctoral position / France  /  Montpellier  /  INSERM U583  /  INSERM U583
Internet Address: http://141.80.163.78/outputid.asp?Code=505
===============================================
No: 443
Post-doctoral position / France  /  Strasbourg  /  INSERM - Centre de Neurochimie  /  INSERM U575 Physiopathologie du systhme nerveux
Internet Address: http://141.80.163.78/outputid.asp?Code=443
===============================================
No: 
Post-doctoral position / France  /  Paris  /  INSERM U. 567 UMR 8104  /  
Internet Address: http://141.80.163.78/outputid.asp?Code=
===============================================
No: 401
Post-doctoral position / France  /  Montpellier  /  Functional Genomics Laboratory - CCIPE  /  Dept. Neurobiology
Internet Address: http://141.80.163.78/outputid.asp?Code=401
===============================================

GERMANY

No: 551
Post-doctoral position / Germany  /  Frankfurt am Main  /  Merz Pharmaceuticals  /  Behavioural Pharmacology
Internet Address: http://141.80.163.78/outputid.asp?Code=551
===============================================
No: 542
Post-doctoral position / Germany  /  Magdeburg  /  Leibniz-Institut f|r Neurobiologie  /  Visual Development and Plasticity
Internet Address: http://141.80.163.78/outputid.asp?Code=542
===============================================
No: 523
Post-doctoral position / Germany  /  Tuebingen  /  Dept. of Ophthalmology II, Univ. of Tuebingen  /  Retinal Electrodiagnostics Research Group
Internet Address: http://141.80.163.78/outputid.asp?Code=523
===============================================
No: 502
Post-doctoral position / Germany  /  Koeln  /  German Sport University  /  Physiology
Internet Address: http://141.80.163.78/outputid.asp?Code=502
===============================================
No: 463
Post-doctoral position / Germany  /  Berlin  /  Max-Delbrueck-Centrum fuer Molekulare Medizin  /  Max Delbrueck Centrum fuer Molekulare Medizin
Internet Address: http://141.80.163.78/outputid.asp?Code=463
===============================================
No: 516
Graduate Student and Post-doctoral Positions / Germany  /  Frankfurt  /  Institute for Biochemistry, Biocenter  /  currently at: Division of Biological Sciences
Internet Address: http://141.80.163.78/outputid.asp?Code=516
===============================================

ITALY

No: 565
Post-doctoral position / Italy  /  Parma  /  Section of Physiology  /  Dept. Neuroscience
Internet Address: http://141.80.163.78/outputid.asp?Code=565
===============================================
No: 564
Post-doctoral position / Italy  /  Parma  /  Section of Physiology  /  Dept. Neuroscience
Internet Address: http://141.80.163.78/outputid.asp?Code=564
===============================================
No: 498
Post-doctoral position / Italy  /  Milano  /  University of Milano  /  Center of Neuropharmacology-Department of Pharmacological Sciences
Internet Address: http://141.80.163.78/outputid.asp?Code=498
===============================================
No: 483
Post-doctoral position / Italy  /  Rome  /  Santa Lucia Foundation IRCCS (www.hsantalucia.it)  /  Rita Levi Montalcini Center for Brain Repair, Department of Neuroscience
Internet Address: http://141.80.163.78/outputid.asp?Code=483
===============================================
No: 438
Post-doctoral position / Italy  /  Milano  /  DIBIT, Vita-Salute San Raffaele University  /  Neuroscience
Internet Address: http://141.80.163.78/outputid.asp?Code=438
===============================================

NETHERLANDS

No: 568
Post-doctoral position / Netherlands  /  Utrecht  /  Rudolf Magnus Institute or Neurosciences  /  Pharmacology and Anatomy
Internet Address: http://141.80.163.78/outputid.asp?Code=568
===============================================
No: 562
Post-doctoral position / Netherlands  /  Amsterdam  /  The Netherlands Ophthalmic Research Institute  /  Neuromedical Genetics
Internet Address: http://141.80.163.78/outputid.asp?Code=562
===============================================
No: 538
Post-doctoral position / Netherlands  /  Rotterdam  /  Erasmus University  /  Neuroscience
Internet Address: http://141.80.163.78/outputid.asp?Code=538
===============================================

NEW ZEALAND

No: 522
Post-doctoral position / New Zealand  /  Auckland  /  Univ. of Auckland, Faculty of Medical and Health Sciences  /  Department of Physiology
Internet Address: http://141.80.163.78/outputid.asp?Code=522
===============================================

NORWAY

No: 569
Post-doctoral position / Norway  /  University of Oslo  /  Institute of basic medical sciences  /  Department of Anatomy
Internet Address: http://141.80.163.78/outputid.asp?Code=569
===============================================

SWEDEN

No: 481
Post-doctoral position / Sweden  /  Uppsala  /  Uppsala University  /  Department of Cell and Molecular Biology
Internet Address: http://141.80.163.78/outputid.asp?Code=481
===============================================

SWITZERLAND

No: 559
Post-doctoral position / Switzerland  /  Zurich  /  University Hospital of Zurich  /  Laboratory of Brain & Cognition
Internet Address: http://141.80.163.78/outputid.asp?Code=559
===============================================
No: 527
Post-doctoral position / Switzerland  /  Basel/ La Jolla San Diego  /  Novartis Institutes for BioMedical Research  /  Nervous System Research
Internet Address: http://141.80.163.78/outputid.asp?Code=527
===============================================
No: 504
Post-doctoral position / Switzerland  /  Lausanne  /  University of Lausanne  /  Institut de Biologie Cellulaire et de Morphologie
Internet Address: http://141.80.163.78/outputid.asp?Code=504
===============================================

UNITED KINGDOM

No: 566
Post-doctoral position / UK  /  London  /  Institute of Neurology, UCL  /  Clinical and Experimental Epilepsy
Internet Address: http://141.80.163.78/outputid.asp?Code=566
===============================================
No: 560
Post-doctoral position / UK  /  London  /  University College London  /  Obs&Gynae, Centre for Perinat Brain Protection and Repair
Internet Address: http://141.80.163.78/outputid.asp?Code=560
===============================================
No: 555
Post-doctoral position / UK  /  London  /  University College London  /  Obs&Gynae, Anatomy
Internet Address: http://141.80.163.78/outputid.asp?Code=555
===============================================
No: 553
Post-doctoral position / UK  /  Birmingham  /  University of Birmingham  /  University Lab Physiology
Internet Address: http://141.80.163.78/outputid.asp?Code=553
===============================================
No: 552
Post-doctoral position / UK  /  Birmingham  /  University of Birmingham  /  University Lab Physiology
Internet Address: http://141.80.163.78/outputid.asp?Code=552
===============================================
No: 540
Research Assistant / UK  /  London  /  University College London  /  Neural Development Unit
Internet Address: http://141.80.163.78/outputid.asp?Code=540
===============================================


U.S.A.

No: 571
Post-doctoral position / USA  /  New York  /  Mount Sinai School of Medicine  /  Psychiatry
Internet Address: http://141.80.163.78/outputid.asp?Code=571
===============================================
No: 563
Post-doctoral position / USA  /  Portland  /  Oregon National Primate Research Center  /  Division of Neuroscience
Internet Address: http://141.80.163.78/outputid.asp?Code=563
===============================================
No: 524
Post-doctoral position / USA  /  San Antonio  /  University of Texas Health Science Center  /  Pharmacology
Internet Address: http://141.80.163.78/outputid.asp?Code=524
===============================================
No: 503
Post-doctoral position / USA  /  Ann Arbor  /  University of Michigan  /  Internal Medicine- Physiology and Neuroscience
Internet Address: http://141.80.163.78/outputid.asp?Code=503
===============================================
No: 474
Post-doctoral position / USA  /  Ann Arbor  /  University of Michigan  /  Molecular and Integrative Physiology
Internet Address: http://141.80.163.78/outputid.asp?Code=474
===============================================
No: 462
Post-doctoral position / USA  /  St. Louis, MO  /  Washington University School of Medicine  /  Neurology
Internet Address: http://141.80.163.78/outputid.asp?Code=462
===============================================
No: 433
Post-doctoral position / USA  /  Tucson  /  University of Arizona  /  Neural Systems, Memory & Aging
Internet Address: http://141.80.163.78/outputid.asp?Code=433
===============================================
No: 312
Post-doctoral position / USA  /  Boston  /  Harvard Medical School - MGH  /  Neurology
Internet Address: http://141.80.163.78/outputid.asp?Code=312
===============================================
No: 394
Post-doctoral position / USA  /  Boston  /  Harvard Medical School  /  Neurology
Internet Address: http://141.80.163.78/outputid.asp?Code=394
===============================================

----------------------------------
PROFESSORS
-----------------------------------


AUSTRIA

No: 576
Professor / Austria  /  Vienna  /  University of Vienna School of Medicine  /  Brain Research Institute
Internet Address: http://141.80.163.78/outputid.asp?Code=576
===============================================

U.S.A.

No: 574
Professor / USA  /  Evanston, Illinois (Chicago, I  /    /  Mechanical Engineering
Internet Address: http://141.80.163.78/outputid.asp?Code=574
===============================================


--------------------------------------------
TECHNICAL POSITIONS
--------------------------------------------

UNITED KINGDOM

No: 575
Technician / UK  /  Brighton  /  University of Sussex  /  Psychology
Internet Address: http://141.80.163.78/outputid.asp?Code=575

===============================================


---------------------------------------------
COMMERCIAL POSITIONS
----------------------------------------------


ITALY

No: 544
Commercial position / Italy  /    /  Noldus Information Technology  /  Sales department
Internet Address: http://141.80.163.78/outputid.asp?Code=544
===============================================

SPAIN

No: 545
Commercial position / Spain  /    /  Noldus Information Technology  /  Sales department
Internet Address: http://141.80.163.78/outputid.asp?Code=545
===============================================


Vera Heinemann
FENS Office Berlin
Max-Delbrueck-Center for Molecular Medicine (MDC)
Robert-Roessle-Str. 10
D-13092 Berlin
Phone: +49 30 9406 3336
Fax: +49 30 9406 3819
e-mail: v.heinemann@mdc-berlin.de


