From simona.grigorescu@philips.com Mon Nov 24 10:01:54 2003
Return-Path: <simona.grigorescu@philips.com>
Received: from gw-nl5.philips.com (gw-nl5.philips.com [212.153.235.109])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAO92dOj003982
	for <M.Bulacu@ai.rug.nl>; Mon, 24 Nov 2003 10:02:39 +0100
Received: from smtpscan-nl1.philips.com (smtpscan-nl1.philips.com [130.139.36.21])
	by gw-nl5.philips.com (Postfix) with ESMTP
	id 11DD161206; Mon, 24 Nov 2003 10:02:38 +0100 (MET)
Received: from smtpscan-nl1.philips.com (localhost [127.0.0.1])
	by localhost.philips.com (Postfix) with ESMTP
	id E9DD019C53; Mon, 24 Nov 2003 10:02:37 +0100 (MET)
Received: from smtprelay-nl2.philips.com (smtprelay-eur2.philips.com [130.139.36.35])
	by smtpscan-nl1.philips.com (Postfix) with ESMTP
	id A1BE319C4E; Mon, 24 Nov 2003 10:02:35 +0100 (MET)
Received: from ehv001soh.diamond.philips.com (e2soh01.diamond.philips.com [130.139.52.13]) 
	by smtprelay-nl2.philips.com (8.9.3p3/8.8.5-1.2.2m-19990317) with ESMTP id KAA03985; Mon, 24 Nov 2003 10:02:35 +0100 (MET)
From: simona.grigorescu@philips.com
To: D.J.Kamerman@cs.rug.nl,
 michel@cs.rug.nl,
 A.Jalba@cs.rug.nl,
 wink@cs.rug.nl,
 michael@cs.rug.nl,
 K.de.Raedt@cs.rug.nl,
 bekker@cs.rug.nl,
 M.Bulacu@ai.rug.nl,
 m.i.bulacu@phys.rug.nl,
 gchezan@yahoo.com,
 pkr@oce.nl
Subject: {Spam?} Photos
MIME-Version: 1.0
X-Mailer: Lotus Notes Release 5.0.9a  January 7, 2002
Message-ID: <OF667D6A02.A2BFD4FD-ONC1256DE8.00310BF6-C1256DE8.00318AD7@diamond.philips.com>
Date: Mon, 24 Nov 2003 10:01:54 +0100
X-MIMETrack: Serialize by Router on ehv001soh/H/SERVER/PHILIPS(Release 5.0.11  |July 24, 2002) at
 24/11/2003 10:00:45,
	Serialize complete at 24/11/2003 10:00:45
Content-Type: multipart/alternative;
  boundary="=_alternative 00318AD4C1256DE8_="
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: spam, SpamAssassin (score=4.2, required 4,
	NORMAL_HTTP_TO_IP 1.28, NO_REAL_NAME 1.28, SPAM_PHRASE_05_08 1.64)
X-ai-MailScanner-SpamScore: ssss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

This is a multipart message in MIME format.
--=_alternative 00318AD4C1256DE8_=
Content-Type: text/plain; charset="us-ascii"

Dear all,

Here are some photos from my Ph.D. defense. I hope that you will like 
them.

http://80.56.8.244/simona/phd_defense/

Simona

P.S. Michael, the photos are great. Thank you very much!

Simona Grigorescu
Philips Medical Systems
P.O. Box 10.000
5680 DA Best
tel: +31 40 27 64778
fax: +31 40 27 62379

--=_alternative 00318AD4C1256DE8_=
Content-Type: text/html; charset="us-ascii"


<br><font size=2 face="sans-serif">Dear all,</font>
<br>
<br><font size=2 face="sans-serif">Here are some photos from my Ph.D. defense. I hope that you will like them.</font>
<br>
<br><font size=2 face="Courier New">http://80.56.8.244/simona/phd_defense/</font>
<br>
<br><font size=2 face="sans-serif">Simona</font>
<br>
<br><font size=2 face="sans-serif">P.S. Michael, the photos are great. Thank you very much!</font>
<br><font size=2 face="sans-serif"><br>
Simona Grigorescu<br>
Philips Medical Systems<br>
P.O. Box 10.000<br>
5680 DA Best<br>
tel: +31 40 27 64778<br>
fax: +31 40 27 62379<br>
</font>
--=_alternative 00318AD4C1256DE8_=--


