From new-member-1-10@boldfish.ieee.org Thu Oct 16 20:01:21 2003
Return-Path: <owner-new-member-1-6@boldfish.ieee.org>
Received: from boldfish (boldfish.ieee.org [140.98.194.25])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id h9GI1UqR011473
	for <m.bulacu@ai.rug.nl>; Thu, 16 Oct 2003 20:01:30 +0200
Received: from boldfish.ieee.org (boldfish [140.98.194.25])
	by boldfish (8.9.3+Sun/8.9.3) with ESMTP id OAA19766
	for <m.bulacu@ai.rug.nl>; Thu, 16 Oct 2003 14:01:25 -0400 (EDT)
Date: Thu, 16 Oct 2003 14:01:21 EDT
Reply-To: ieeemd@ieee.org
Message-Id: <A10663272811249389572@boldfish.ieee.org>
From: new-member-1-10@boldfish.ieee.org
Sender: owner-new-member-1-6@boldfish.ieee.org
Mime-Version: 1.0
X-Sender: owner-new-member-1-6@boldfish.ieee.org
X-Sender: new-member-1-10@boldfish.ieee.org
X-List-Software: "BoldFish Version 2.3.2.2/010905.1" <http://www.boldfish.com>
Subject: 41560649: Welcome To The IEEE
To: m.bulacu@ai.rug.nl
References: <A10663272814939564729.m.bulacu@ai.rug.nl>
Received: from 140.98.194.25 by 140.98.194.25
	with EWP id A10663272814936972323
	for <m.bulacu@ai.rug.nl>; Thu, 16 Oct 2003 14:01:21 EDT
List-Unsubscribe: http://boldfish.ieee.org:8080/unsub/new-member-1-6/m.bulacu%40ai.rug.nl/f1e5c7e51ed3292cce39abe9892f3655/
Content-Type: text/plain;
  charset="us-ascii"
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=3.9, required 4,
	DEAR_SOMEBODY 0.10, FORGED_RCVD_FOUND 0.77, FROM_ENDS_IN_NUMS 0.89,
	MSG_ID_ADDED_BY_MTA_2 0.11, NO_REAL_NAME 1.28, REFERENCES -0.52,
	SPAM_PHRASE_08_13 1.39, SUPERLONG_LINE 0.01,
	SUSPECT_LIST_HEADERS -0.20)
X-ai-MailScanner-SpamScore: sss
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  


Dear  Marius L Bulacu:

Let me extend my personal thanks for your decision to join the IEEE.  

I hope that you have had the opportunity to investigate and take full advantage of the array of benefits that are exclusive to you. If not, please take a moment now to become acquainted with the broad scope of products and services that is available to members by visiting the IEEE home page at http://www.ieee.org/.

I also want to provide you with information on some of the more recent products and services that we have introduced so you may bookmark the sites that are of interest to you:

IEEE Spectrum -  receive monthly issues of IEEE Spectrum Magazine and gain access to members-only content at the IEEE Spectrum Online site.

IEEE Xplore - provides you with electronic access to tables of contents and abstracts/indexes of over 900,000 IEEE articles. In addition, Xplore also provides you with 'full text' access to any of your online subscriptions. http://www.ieee.org/ieeexplore/

Free IEEE e-mail alias - Never again will you have to notify your friends and colleagues of an e-mail address change. Your personal e-mail alias identifies you as an IEEE member, forwards your mail to any account you designate, and provides you with up-to-the-minute virus scanning. Register at http://eleccomm.ieee.org.

IEEE Job Site - The job site that puts you in control!  Create your 'dream job' profile today. You will be notified anonymously of any job postings that match your profile. You choose whether to respond or not. Hey, you never know!  http://careers.ieee.org/. 

IEEE Educational Activities - Thousands of courses are available online to IEEE Members at a 10% Discount. In collaboration with universities and corporate education providers, IEEE offers distance learning graduate degree and certificate programs, and non-credit technical, "soft" skills and general interest courses. To view courses being offered, visit http://www.ieee.org/edupartners.  For information about IEEE educational programs and services, go to www.ieee.org/icet.

Conference Search Service - Find a conference that will keep you on the cutting edge of your technical field. http://www.ieee.org/conferencesearch/

Network - Connect with your local Section for events and meetings near you. http://www.ieee.org/organizations/rab/sec_chap/ 

IEEE Financial Advantage Program - Discounts on insurance, investments, travel, and other great programs.  http://www.ieee.org/services/financial/fap/

Many of the above web-based products and services require you to have an IEEE Web Account for access. If you haven't already done so, you can register for your IEEE Web Account now at http://www.ieee.org/web/accounts/.  

Your opinion counts! To help serve you now and in the future let us know what you think by completing the brief survey at http://www.ieee.org/membership/survey.html or feel free to send me your comments by reply email. 

Sincerely,
Daniel J. Senese, Senior Member 
IEEE Executive Director

**************************************************************************************************


