From J.van.Dijk@ai.rug.nl Mon Nov 24 13:26:04 2003
Return-Path: <J.van.Dijk@ai.rug.nl>
Received: from tcw2.ppsw.rug.nl (localhost [127.0.0.1])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hAOCQ4Oj019784
	for <bulacu@tcw2.ppsw.rug.nl>; Mon, 24 Nov 2003 13:26:04 +0100
Received: (from apache@localhost)
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8/Submit) id hAOCQ4vO019782;
	Mon, 24 Nov 2003 13:26:04 +0100
From: Jeroen van Dijk <J.van.Dijk@ai.rug.nl>
Received: from ppsw139128.ppsw.rug.nl ([129.125.139.128])
        (SquirrelMail authenticated user jvandijk)
        by www.ai.rug.nl with HTTP;
        Mon, 24 Nov 2003 13:26:04 +0100 (CET)
Message-ID: <1399.129.125.139.128.1069676764.squirrel@www.ai.rug.nl>
Date: Mon, 24 Nov 2003 13:26:04 +0100 (CET)
Subject: KI2 - the JAVA package for IO
To: bulacu@ai.rug.nl
User-Agent: SquirrelMail/1.4.2-1
MIME-Version: 1.0
Content-Type: text/plain;
  charset=iso-8859-1
Content-Transfer-Encoding: 8bit
X-Priority: 3
Importance: Normal
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=1.3, required 4,
	PRIORITY_NO_NAME 1.02, SPAM_PHRASE_00_01 0.78, USER_AGENT -0.52)
X-ai-MailScanner-SpamScore: s
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

Hello Marius Bulacu,

Last friday you asked me to make a JAVA class for input/output operations
for the spamfilter. Frank Brokken already made a package we need. I've
made a link to it on my homepage http://www.ai.rug.nl/~jvandijk/ . It's a
RAR file so the only thing you have to do is to decompress it.

I think that most of the students have worked with this package on a
introduction JAVA course. So there's no documentation needed.

Regards,

Jeroen van Dijk


