From ilie_bulacu@fx.ro Tue Nov  4 06:53:42 2003
Return-Path: <ilie_bulacu@fx.ro>
Received: from corporate.fx.ro (corporate.fx.ro [193.231.208.29])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hA45L5af002669
	for <m.bulacu@ai.rug.nl>; Tue, 4 Nov 2003 06:21:05 +0100
Received: from mail.fx.ro (mail4.fx.ro [193.231.208.4])
	by corporate.fx.ro (8.12.10/8.12.7) with ESMTP id hA45L6ls012757;
	Tue, 4 Nov 2003 07:21:06 +0200
Received: from ilie (ppp24122.fx.ro [195.7.2.122])
	by mail.fx.ro (8.12.10/8.12.3) with SMTP id hA45KsDH027758;
	Tue, 4 Nov 2003 07:20:55 +0200
Message-ID: <000801c3a298$29d72480$7a0207c3@ilie>
From: "ILIE BULACU" <ilie_bulacu@fx.ro>
To: <mbulacu@hotmail.com>,
 <m.bulacu@ai.rug.nl>
Cc: <m.i.bulacu@phys.rug.nl>
Subject: Fw: China Becomes Only Third Nation to Put Man in Space
Date: Tue, 4 Nov 2003 07:53:42 +0200
MIME-Version: 1.0
Content-Type: multipart/alternative;
  boundary="----=_NextPart_000_0005_01C3A2A8.C4163120"
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 5.00.2615.200
X-MimeOLE: Produced By Microsoft MimeOLE V5.00.2615.200
X-RAVMilter-Version: 8.4.3(snapshot 20030212) (mail)
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=0.6, required 4,
	OUTLOOK_FW_MSG -0.07, SPAM_PHRASE_01_02 0.50, USER_AGENT_OE 0.18)
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

This is a multi-part message in MIME format.

------=_NextPart_000_0005_01C3A2A8.C4163120
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

China Becomes Only Third Nation to Put Man in Space

By Brian Rhoads

BEIJING (Reuters) - China put its first man in space on Wednesday, =
sending a single astronaut on a
21-hour odyssey around the Earth four decades after the Soviet Union and =
the United States pioneered
manned space flight.

The Long March 2F rocket carrying "taikonaut" Yang Liwei lifted off into =
a clear blue sky over the Gobi
desert at 9 a.m. (9 p.m. EDT) and entered its predetermined orbit 10 =
minutes later.

The official Xinhua news agency quickly declared the launch a success.

"I feel good and my conditions are normal", Xinhua quoted Yang as saying =
from space as the Shenzhou
V, or "Divine Ship V", was making its first pass around the Earth.

Yang, 38, is part of an historic mission which, if completed, will make =
China just the third nation
to successfully put a man into space -- and return him to Earth -- over =
40 years behind the former
Soviet Union and the United States.

At the Jiuquan Space Center onlookers clapped and cheered as the =
Shenzhou V rocket lifted off into
a clear blue sky.

A thousand miles away in the capital, pride was mixed with relief as =
state television broadcast delayed
pictures of the launch -- after a safe interval and an official =
declaration that the launch had been
a success.

The launch was a boost for the leaders of the world's most populous =
nation. President Hu Jintao,
who witnessed the lift-off, spoke of the "glory of our great =
motherland."

Economists played down the commercial implications of the mission.

"The economic benefit of such a launch is pretty minimal", said Tai Hui =
with Standard Chartered
in Hong Kong. "It is a show of muscle, a show of power to the region."

"YOUNG PIONEERS"

Earlier, decked out in his space suit, Yang had headed for the launch =
past rows of beaming and
balloon-carrying children, "Young Pioneers" who had come to see him off. =
Once in the capsule
he reviewed a flight manual and appeared "composed and at ease", Xinhua =
said.

In the United States, NASA (news - web sites) Administrator Sean O'Keefe =
described the launch
as an important achievement for China.

"The Chinese people have a long and distinguished history of =
exploration", he said in a statement.
"NASA wishes China a continued safe human space flight program."

Japan added its praise. "We want to offer our congratulations for the =
success from the bottom of
our heart", Chief Cabinet Secretary Yasuo Fukuda said.

State media hailed the spacecraft as China's most sophisticated, with =
breakthrough technology
including fault-detection and escape systems.

SIMPLY THE BEST

Quoted by the China Daily, Huang Chunping, commander-in-chief of rocket =
systems, said: "The rocket
that will launch the Shenzhou V spaceship is the best of all. It is of =
superior quality and has stood our
most stringent testing."

Speaking at Jiuquan, President Hu described Wednesday's success as a =
"mark for the initial victory
of the country's first manned space flight and for the significant, =
historic step by the Chinese people
in scaling the peak of the world's science and technology", Xinhua =
quoted Hu as saying.

Yang, who follows a trail blazed by Russian cosmonaut Yuri Gagarin and =
American Alan Shepard in
1961, was due to orbit the Earth 14 times and touch down in Inner =
Mongolia at 7 a.m. on Thursday
(7 p.m. EDT on Wednesday).

A lieutenant colonel in the People's Liberation Army selected from a =
pool of 14, Yang is the son of
a teacher and an official at an agricultural firm.
He was raised in Suizhong county in the northeast "rustbelt" province of =
Liaoning.

"We are proud of him", his brother-in-law told Reuters just minutes =
before the launch.
"We don't worry about his safety because we trust the nation's advanced =
technology."

Yang was to dine on specially designed packets of shredded pork with =
garlic and "eight treasure" rice,
washed down with Chinese tea, state media said.

A successful mission would mark the crowning moment for a space program =
launched by Mao Zedong
in 1958 but quickly left far behind in the Cold War "space race" rivalry =
that saw the United States put a
man on the moon in 1969.

"THE EAST IS RED"

A year later, China launched its first satellite aboard a Long March =
rocket, which orbited the Earth
blaring out the Cultural Revolution anthem "The East is Red."

A tight veil of secrecy has blanketed the space program and the =
58.3-meter-high (191-foot-high),
479.8-toncraft.

Success would spur China's scientific programs and emergence on the =
world stage marked by more
active diplomacy, a winning bid to host the 2008 Olympics and a robust =
economy.

Failure would lead to a national bout of hand wringing and cast a sharp =
spotlight on China's many
problems, from unemployment to disgruntled peasants to a growing gap =
between rich and poor.

China invented gunpowder and legend has it that a Ming dynasty =
(1368-1644) official named Wan Hu
attempted the world's first space launch.
He strapped himself to a chair with kites in each hand as 47 servants =
lit 47 gunpowder-packed bamboo
tubes tied to the seat.

When the smoke had cleared, Wan was apparently found to have been =
obliterated. But the dream was
not.

------=_NextPart_000_0005_01C3A2A8.C4163120
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META content=3D"text/html; charset=3Diso-8859-1" =
http-equiv=3DContent-Type>
<META content=3D"MSHTML 5.00.2614.3500" name=3DGENERATOR>
<STYLE></STYLE>
</HEAD>
<BODY bgColor=3D#ffffff>
<DIV><FONT face=3DArial size=3D2>China Becomes Only Third Nation to Put =
Man in=20
Space</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>By Brian Rhoads</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>BEIJING (Reuters) - China put its first =
man in=20
space on Wednesday, sending a single astronaut on a</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>21-hour odyssey around the Earth four =
decades after=20
the Soviet Union and the United States pioneered</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>manned space flight.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>The Long March 2F rocket carrying =
"taikonaut" Yang=20
Liwei lifted off into a clear blue sky over the Gobi</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>desert at 9 a.m. (9 p.m. EDT) and =
entered its=20
predetermined orbit 10 minutes later.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>The official Xinhua news agency quickly =
declared=20
the launch a success.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>"I feel good and my conditions are =
normal", Xinhua=20
quoted Yang as saying from space as the Shenzhou</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>V, or "Divine Ship V", was making its =
first pass=20
around the Earth.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Yang, 38, is part of an historic =
mission which, if=20
completed, will make China just the third nation</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>to successfully put a man into space -- =
and return=20
him to Earth -- over 40 years behind the former</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>Soviet Union and the United =
States.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>At the Jiuquan Space Center onlookers =
clapped and=20
cheered as the Shenzhou V rocket lifted off into</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>a clear blue sky.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>A thousand miles away in the capital, =
pride was=20
mixed with relief as state television broadcast delayed</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>pictures of the launch -- after a safe =
interval and=20
an official declaration that the launch had been</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>a success.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>The launch was a boost for the leaders =
of the=20
world's most populous nation. President Hu Jintao,</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>who witnessed the lift-off, spoke of =
the "glory of=20
our great motherland."</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Economists played down the commercial =
implications=20
of the mission.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>"The economic benefit of such a launch =
is pretty=20
minimal", said Tai Hui with Standard Chartered</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>in Hong Kong. "It is a show of muscle, =
a show of=20
power to the region."</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>"YOUNG PIONEERS"</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Earlier, decked out in his space suit, =
Yang had=20
headed for the launch past rows of beaming and</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>balloon-carrying children, "Young =
Pioneers" who had=20
come to see him off. Once in the capsule</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>he reviewed a flight manual =
</FONT><FONT face=3DArial=20
size=3D2>and appeared "composed and at ease", Xinhua said.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>In the United States, NASA (news - web =
sites)=20
Administrator Sean O'Keefe described the launch</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>as an important achievement for =
China.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>"The Chinese people have a long and =
distinguished=20
history of exploration", he said in a statement.<BR>"NASA wishes China a =

continued safe human space flight program."</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Japan added its praise. "We want to =
offer our=20
congratulations for the success from the bottom of</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>our heart", Chief Cabinet Secretary =
Yasuo Fukuda=20
said.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>State media hailed the spacecraft as =
China's most=20
sophisticated, with breakthrough technology</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>including fault-detection and escape=20
systems.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>SIMPLY THE BEST</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Quoted by the China Daily, Huang =
Chunping,=20
commander-in-chief of rocket systems, said: "The rocket</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>that will launch the Shenzhou V =
spaceship is the=20
best of all. It is of superior quality and has stood our</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>most stringent testing."</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Speaking at Jiuquan, President Hu =
described=20
Wednesday's success as a "mark for the initial victory</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>of the country's first manned space =
flight and for=20
the significant, historic step by the Chinese people</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>in scaling the peak of the world's =
science and=20
technology", Xinhua quoted Hu as saying.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Yang, who follows a trail blazed by =
Russian=20
cosmonaut Yuri Gagarin and American Alan Shepard in</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>1961, was due to orbit the Earth 14 =
times and touch=20
down in Inner Mongolia at 7 a.m. on Thursday</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>(7 p.m. EDT on Wednesday).</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>A lieutenant colonel in the People's =
Liberation=20
Army selected from a pool of 14, Yang is the son of</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>a teacher and an official at an =
agricultural=20
firm.<BR>He was raised in Suizhong county in the northeast "rustbelt" =
province=20
of Liaoning.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>"We are proud of him", his =
brother-in-law told=20
Reuters just minutes before the launch.<BR>"We don't worry about his =
safety=20
because we trust the nation's advanced technology."</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Yang was to dine on specially designed =
packets of=20
shredded pork with garlic and "eight treasure" rice,</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>washed down with Chinese tea, state =
media=20
said.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>A successful mission would mark the =
crowning moment=20
for a space program launched by Mao Zedong</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>in 1958 but quickly left far behind in =
the Cold War=20
"space race" rivalry that saw the United States put a</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>man on the moon in 1969.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>"THE EAST IS RED"</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>A year later, China launched its first =
satellite=20
aboard a Long March rocket, which orbited the Earth</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>blaring out the Cultural Revolution =
anthem "The=20
East is Red."</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>A tight veil of secrecy has blanketed =
the space=20
program and the 58.3-meter-high (191-foot-high),</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>479.8-toncraft.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Success would spur China's scientific =
programs and=20
emergence on the world stage marked by more</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>active diplomacy, a winning bid to host =
the 2008=20
Olympics and a robust economy.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Failure would lead to a national bout =
of hand=20
wringing and cast a sharp spotlight on China's many</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>problems, from unemployment to =
disgruntled peasants=20
to a growing gap between rich and poor.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>China invented gunpowder and legend has =
it that a=20
Ming dynasty (1368-1644) official named Wan Hu</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>attempted the world's first space =
launch.<BR>He=20
strapped himself to a chair with kites in each hand as 47 servants lit =
47=20
gunpowder-packed bamboo</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>tubes tied to the seat.</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>When the smoke had cleared, Wan was =
apparently=20
found to have been obliterated. But the dream was</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>not.</DIV></FONT></BODY></HTML>

------=_NextPart_000_0005_01C3A2A8.C4163120--


