From v.heinemann@mdc-berlin.de Thu Oct 23 20:22:51 2003
Return-Path: <v.heinemann@mdc-berlin.de>
Received: from server1.bbb2.mdc-berlin.de (server1.bbb2.mdc-berlin.de [141.80.34.10])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id h9NIMqqR031214
	for <m.bulacu@ai.rug.nl>; Thu, 23 Oct 2003 20:22:52 +0200
Received: from vheine ([141.80.161.92])
	by server1.bbb2.mdc-berlin.de (8.12.10/8.12.10) with SMTP id h9NIMpeN026950
	for <m.bulacu@ai.rug.nl>; Thu, 23 Oct 2003 20:22:51 +0200 (METDST)
Date: Thu, 23 Oct 2003 20:22:51 +0200 (METDST)
Message-Id: <200310231822.h9NIMpeN026950@server1.bbb2.mdc-berlin.de>
From: FENS Office Berlin<v.heinemann@mdc-berlin.de>
To: m.bulacu@ai.rug.nl
Subject: European Journal of Neuroscience: Volume 18, Issue 8, Oct 2003
Mime-Version: 1.0
Content-Type: text/plain;
  charset=us-ascii
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=-0.7, required 4,
	CLICK_BELOW 0.31, FORGOTTEN_PASSWORD -1.13, MEMBER_2 0.29,
	SPAM_PHRASE_00_01 0.78, SUBJECT_MONTH -0.48, SUBJECT_MONTH_2 -0.48)
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  


Dear FENS Member,

Please find enclosed the Table of Contents Alert for the 
European Journal of Neuroscience: Volume 18, Issue 8, Oct 2003 
------------------------------------------------------------------------ 

The above issue is now available online from Blackwell Synergy at: 

http://www.blackwell-synergy.com/links/toc/ejn/18/8 

The table of contents for this issue is listed below. Click on the links 
below to view the abstract for each article, or click on the link above 
to read the table of contents online. 

If you have forgotten your password or need any further help, please visit 
www.blackwell-synergy.com and click on "help". 

------------------------------------------------------------------------ 
Review Article 
------------------------------------------------------------------------ 
Ascending visceral regulation of cortical affective information 
processing 

Gary G. Berntson, Martin Sarter, John T. Cacioppo 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2103 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02967.x 

------------------------------------------------------------------------ 
Research Reports 
------------------------------------------------------------------------ 
Contribution of Kir3.1, Kir3.2A and Kir3.2C subunits to native G 
protein-gated inwardly rectifying potassium currents in cultured 
hippocampal neurons 

Joanne L. Leaney 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2110 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02933.x 

------------------------------------------------------------------------ 
The coding of odour-intensity in the honeybee antennal lobe: local 
computation optimizes odour representation 

Silke Sachse, C. Giovanni Galizia 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2119 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02931.x 

------------------------------------------------------------------------ 
Involvement of transient receptor potential-like channels in responses 
to mGluR-I activation in midbrain dopamine neurons 

Alessandro Tozzi, C. Peter Bengtson, Patrizia Longone, Corrado 
Carignani, Francesca R. Fusco, Giorgio Bernardi, Nicola B. Mercuri 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2133 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02936.x 

------------------------------------------------------------------------ 
Extrinsic regulation of injury/growth-related gene expression in the 
inferior olive of the adult rat 

Annalisa Buffo, Daniela Carulli, Ferdinando Rossi, Piergiorgio Strata 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2146 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02940.x 

------------------------------------------------------------------------ 
Differential arithmetic of shunting inhibition for voltage and spike 
rate in neocortical pyramidal cells 

Daniel Ulrich 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2159 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02942.x 

------------------------------------------------------------------------ 
Elimination of serotonergic cells induces a marked increase in 
generation of dopaminergic neurons from mesencephalic precursors 

Jannette Rodriguez-Pallares, Maria J. Guerra, Jose L. Labandeira-Garcia 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2166 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02949.x 

------------------------------------------------------------------------ 
Development of Ca2+-channel and BK-channel expression in embryos and 
larvae of Xenopus laevis 

Cristina Jimenez-Gonzalez, Gerald J. McLaren, Nicholas Dale 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2175 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02955.x 

------------------------------------------------------------------------ 
Generation and phenotypic analysis of sigma receptor type I (sigma1) 
knockout mice 

Francina Langa, Xavier Codony, Victoria Tovar, Alfonso Lavado, Estela 
Gimenez, Patricia Cozar, Marta Cantero, Albert Dordal, Enric Hernandez, 
Raquel Perez, Xavier Monroy, Daniel Zamanillo, Xavier Guitart, Lluis 
Montoliu 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2188 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02950.x 

------------------------------------------------------------------------ 
Cannabinoid receptor and WIN 55 212-2-stimulated [35S]-GTPgammaS binding 
in the brain of mu-, delta- and kappa-opioid receptor knockout mice 

Fernando Berrendero, Victoria Mendizabal, Patricia Murtra, Brigitte L. 
Kieffer, Rafael Maldonado 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2197 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02951.x 

------------------------------------------------------------------------ 
Sex hormone-dependent desensitization of 5-HT1A autoreceptors in 
knockout mice deficient in the 5-HT transporter 

Saoussen Bouali, Alexis Evrard, Michel Chastanet, Klaus-Peter Lesch, 
Michel Hamon, Joelle Adrien 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2203 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02960.x 

------------------------------------------------------------------------ 
Rapid and long-term alterations of hippocampal GABAB receptors in a 
mouse model of temporal lobe epilepsy 

Andrea Straessle, Fabienne Loup, Dimitrula Arabadzisz, Gordon V. Ohning, 
Jean-Marc Fritschy 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2213 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02964.x 

------------------------------------------------------------------------ 
Distribution and pharmacology of alanine-serine-cysteine transporter 1 
(asc-1) in rodent brain 

Lone Helboe, Jan Egebjerg, Morten Moller, Christian Thomsen 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2227 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02966.x 

------------------------------------------------------------------------ 
Activation of peripheral cannabinoid CB1 receptors inhibits mechanically 
evoked responses of spinal neurons in noninflamed rats and rats with 
hindpaw inflammation 

Sara Kelly, Maulik D. Jhaveri, Devi R. Sagar, David A. Kendall, Victoria 
Chapman 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2239 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02957.x 

------------------------------------------------------------------------ 
MuSC is involved in regulating axonal fasciculation of mouse primary 
vestibular afferents 

Daisuke Kawauchi, Hiroaki Kobayashi, Yoko Sekine-Aizawa, Shinobu C. 
Fujita, Fujio Murakami 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2244 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02968.x 

------------------------------------------------------------------------ 
Increasing local levels of neuregulin (glial growth factor-2) by direct 
infusion into areas of demyelination does not alter remyelination in the 
rat CNS 

Jacques Penderis, Rachel H. Woodruff, Andras Lakatos, Wen-Wu Li, Mark D. 
Dunning, Chao Zhao, Mark Marchionni, Robin J. M. Franklin 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2253 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02969.x 

------------------------------------------------------------------------ 
Down-regulation of CYP1A2 induction during the maturation of mouse 
cerebellar granule cells in culture: role of nitric oxide accumulation 

Sonia Mulero-Navarro, Belen Santiago-Josefat, Eulalia Pozo-Guisado, 
Jaime M. Merino, Pedro M. Fernandez-Salguero 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2265 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02972.x 

------------------------------------------------------------------------ 
Networks of inhibitory and excitatory commissural interneurons mediating 
crossed reticulospinal actions 

B. Anne Bannatyne, Stephen A. Edgley, Ingela Hammar, Elzbieta Jankowska, 
David J. Maxwell 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2273 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02973.x 

------------------------------------------------------------------------ 
Histaminergic facilitation of electrocorticographic activation: role of 
basal forebrain, thalamus, and neocortex 

Hans C. Dringenberg, Min-Ching Kuo 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2285 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02975.x 

------------------------------------------------------------------------ 
Hippocampal N-acetyl aspartate levels do not mirror neuronal cell 
densities in creatine-supplemented epileptic rats 

Stefan Vielhaber, Alexei P. Kudin, Tatiana A. Kudina, Detlef Stiller, 
Henning Scheich, Ariel Schoenfeld, Helmut Feistner, Hans-Jochen Heinze, 
Christian E. Elger, Wolfram S. Kunz 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2292 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02954.x 

------------------------------------------------------------------------ 
Mapping responses to frequency sweeps and tones in the inferior 
colliculus of house mice 

Steffen R. Hage, Gunter Ehret 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2301 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02945.x 

------------------------------------------------------------------------ 
Mice with astrocyte-directed inactivation of connexin43 exhibit 
increased exploratory behaviour, impaired motor capacities, and changes 
in brain acetylcholine levels 

Christian Frisch, Martin Theis, Maria A. De Souza Silva, Ekrem Dere, 
Goran Sohl, Barbara Teubner, Katerina Namestkova, KIaus Willecke, Joseph 
P. Huston 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2313 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02971.x 

------------------------------------------------------------------------ 
Haploinsufficiency in trkB and/or trkC neurotrophin receptors causes 
structural alterations in the aged hippocampus and amygdala 

Oliver von Bohlen und Halbach, Liliana Minichiello, Klaus Unsicker 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2319 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02953.x 

------------------------------------------------------------------------ 
Selective psychostimulant sensitization by food restriction: 
differential changes in accumbens shell and core dopamine 

Cristina Cadoni, Marcello Solinas, Valentina Valentini, Gaetano Di 
Chiara 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2326 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02941.x 

------------------------------------------------------------------------ 
Temporal aspects of spatial task performance during intermittent hypoxia 
in the rat: evidence for neurogenesis 

David Gozal, Barry W. Row, Evelyne Gozal, Leila Kheirandish, Jennifer J. 
Neville, Kenneth R. Brittian, Leroy R. Sachleben, Shang Z. Guo 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2335 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02947.x 

------------------------------------------------------------------------ 
Differential contributions of the basolateral and central nuclei of the 
amygdala in the negative affective component of chemical somatic and 
visceral pains in rats 

Sachi Tanimoto, Takayuki Nakagawa, Yosuke Yamauchi, Masabumi Minami, 
Masamichi Satoh 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2343 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02952.x 

------------------------------------------------------------------------ 
Augmentation of induced visual gamma activity by increased task 
complexity 

Andres Posada, Etienne Hugues, Nicolas Franck, Pascal Vianin, James 
Kilner 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2351 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02962.x 

------------------------------------------------------------------------ 
The medial prefrontal cortex differentially regulates stress-induced 
c-fos expression in the forebrain depending on type of stressor 

Helmer F. Figueiredo, Amy Bruestle, Bryan Bodie, Charles M. Dolgas, 
James P. Herman 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2357 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02932.x 

------------------------------------------------------------------------ 
Distinct roles of the different ionotropic glutamate receptors within 
the nucleus accumbens in passive-avoidance learning and memory in mice 

Elvira De Leonibus, Vivian J. A. Costantini, Claudio Castellano, 
Valentina Ferretti, Alberto Oliverio, Andrea Mele 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2365 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02939.x 

------------------------------------------------------------------------ 
Attention and working memory: a dynamical model of neuronal activity in 
the prefrontal cortex 

Gustavo Deco, Edmund T. Rolls 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2374 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02956.x 

------------------------------------------------------------------------ 
Self-face processing in a callosotomy patient 

Julian Paul Keenan, Mark Wheeler, Steven M. Platek, Gina Lardi, Maryse 
Lassonde 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2391 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02958.x 

------------------------------------------------------------------------ 
Predictive and reactive co-ordination of grip and load forces in 
bimanual lifting in man 

R. Martyn Bracewell, Alan M. Wing, Harriet M. Soper, Kristen G. Clark 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2396 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02944.x 

------------------------------------------------------------------------ 
Short Communications 
------------------------------------------------------------------------ 
Molecular scaffold reorganization at the transmitter release site with 
vesicle exocytosis or botulinum toxin C1 

Elise F. Stanley, Tom S. Reese, Gary Z. Wang 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2403 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02948.x 

------------------------------------------------------------------------ 
Attention capture by auditory significant stimuli: semantic analysis 
follows attention switching 

Carles Escera, Elena Yago, Maria-Jose Corral, Silvia Corbera, M. Isabel 
Nunez 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2408 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02937.x 

------------------------------------------------------------------------ 
Lesions of the mammillothalamic tract impair the acquisition of spatial 
but not nonspatial contextual conditional discriminations 

Seralynne D. Vann, R. C. Honey, John P. Aggleton 
European Journal of Neuroscience; Volume 18, Issue 8, Page 2413 

http://www.blackwell-synergy.com/links/doi/10.1046/j.1460-9568.2003.02959.x 

------------------------------------------------------------------------ 


Vera Heinemann
FENS Office Berlin
Max-Delbrueck-Center for Molecular Medicine (MDC)
Robert-Roessle-Str. 10
D-13092 Berlin
Phone: +49 30 9406 3336
Fax: +49 30 9406 3819
e-mail: v.heinemann@mdc-berlin.de


