From C.BEUKEMA@ppsw.rug.nl Wed Dec  3 11:08:25 2003
Return-Path: <C.BEUKEMA@ppsw.rug.nl>
Received: from dep.ppsw.rug.nl (dep.ppsw.rug.nl [129.125.153.250])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hB3A8mOj024795
	for <M.Bulacu@tcw2.ai.rug.nl>; Wed, 3 Dec 2003 11:08:48 +0100
Received: from PPSWMERC.ppsw.rug.nl (ppswmerc.ppsw.rug.nl [129.125.153.242])
	by dep.ppsw.rug.nl (8.9.3p3/8.9.3) with ESMTP id LAA30237
	for <M.Bulacu@ai.rug.nl>; Wed, 3 Dec 2003 11:08:48 +0100
Message-Id: <200312031008.LAA30237@dep.ppsw.rug.nl>
Received: from PPSWMERC/SpoolDir by PPSWMERC.ppsw.rug.nl (Mercury 1.48);
    3 Dec 03 11:08:49 +0100
Received: from SpoolDir by PPSWMERC (Mercury 1.48); 3 Dec 03 11:08:28 +0100
From: "C. Beukema" <C.BEUKEMA@ppsw.rug.nl>
Organization: Faculteit PPSW RuG
To: Marius Bulacu <M.Bulacu@ai.rug.nl>
Date: Wed, 3 Dec 2003 11:08:25 +0100
MIME-Version: 1.0
Content-type: text/plain;
  charset=US-ASCII
Content-transfer-encoding: 7BIT
Subject: Re: [Staf] Biertjes voor allemaal
Priority: normal
In-reply-to: <Pine.LNX.4.53.0312030951470.9472@aix4.ai.rug.nl>
X-mailer: Pegasus Mail for Win32 (v3.11)
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam (whitelisted),
	SpamAssassin (score=-100.9, required 4, IN_REP_TO -0.85,
	MSG_ID_ADDED_BY_MTA_2 0.11, NOSPAM_INC -0.21,
	QUOTED_EMAIL_TEXT -0.83, SPAM_PHRASE_00_01 0.78,
	USER_IN_WHITELIST -100.00)
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

Hi Marius,

Congratulations!

Do you know you can use the "biertjes" stocked in the Gert's closet??

Chris


Date sent:      	Wed, 3 Dec 2003 10:02:01 +0100 (CET)
From:           	Marius Bulacu <M.Bulacu@ai.rug.nl>
To:             	staf@ai.rug.nl
Subject:        	[Staf] Biertjes voor allemaal

> 
> Dear colleagues,
> 
> I am very happy to invite you all for a "biertje", today (wednesday, 3 
> dec. 2003) at 16.00. The location is the coffie corner where most of our 
> celebrations take place.
> 
> The happy occasion is caused by the fact that a very important paper 
> written by Lambert and myself was accepted for publication in a big 
> journal: IEEE Transactions on Pattern Analysis and
> Machine Intelligence (PAMI).
> 
> Tot dan,
> 
> 	Marius
> _______________________________________________
> Staf mailing list
> Staf@ai.rug.nl
> http://www.ai.rug.nl/mailman/listinfo/staf


