From d.h.koopmans@med.rug.nl Mon Dec  8 11:47:41 2003
Return-Path: <d.h.koopmans@med.rug.nl>
Received: from medmail.med.rug.nl (medmail.med.rug.nl [129.125.135.2])
	by tcw2.ppsw.rug.nl (8.12.8/8.12.8) with ESMTP id hB89lkOj002894
	for <bulacu@ai.rug.nl>; Mon, 8 Dec 2003 10:47:46 +0100
Received: from mail.med.rug.nl (mail.med.rug.nl [129.125.159.6])
	by medmail.med.rug.nl (8.12.10/8.12.10) with ESMTP id hB89ljb2001771
	for <bulacu@ai.rug.nl>; Mon, 8 Dec 2003 10:47:45 +0100 (MET)
Message-Id: <200312080947.hB89ljb2001771@medmail.med.rug.nl>
Received: from MEDMAILMW1/SpoolDir by mail.med.rug.nl (Mercury 1.48);
    8 Dec 03 10:47:45 GMT+0100
Received: from SpoolDir by MEDMAILMW1 (Mercury 1.48); 8 Dec 03 10:47:43 GMT+0100
From: "D.H.KOOPMANS" <d.h.koopmans@med.rug.nl>
Organization: faculty of medical sciences (RuG)
To: Marius Bulacu <bulacu@ai.rug.nl>
Date: Mon, 8 Dec 2003 10:47:41 GMT+0100
MIME-Version: 1.0
Content-type: text/plain;
  charset=US-ASCII
Content-transfer-encoding: 7BIT
Subject: Re: contribution to the BCN website
X-Confirm-Reading-To: "D.H.KOOPMANS" <d.h.koopmans@med.rug.nl>
X-pmrqc: 1
Priority: normal
References: <200312011502.hB1F27b2008800@medmail.med.rug.nl>
In-reply-to: <Pine.LNX.4.53.0312011635040.3929@aix4.ai.rug.nl>
X-mailer: Pegasus Mail for Win32 (v3.12)
X-Scanned-By: milter-spamc/0.9.102 (medmail [129.125.135.2]); Mon, 08 Dec 2003 10:47:45 %z
X-Spam-Flag: NO
X-Spam-Status: NO, hits=-100.00 required=5.00
X-Spam-Level: 
X-ai-MailScanner-Information: Please contact helpdesk@ai.rug.nl for more information
X-ai-MailScanner: Found to be clean
X-ai-MailScanner-SpamCheck: not spam, SpamAssassin (score=1.3, required 4,
	DEAR_SOMEBODY 0.10, INVALID_DATE 1.52, IN_REP_TO -0.85,
	MSG_ID_ADDED_BY_MTA_2 0.11, NOSPAM_INC -0.21, REFERENCES -0.52,
	SPAM_PHRASE_03_05 1.08)
X-ai-MailScanner-SpamScore: s
Status: RO
X-Status: U
X-KMail-EncryptionState:  
X-KMail-SignatureState:  

dDear Marius,

Thank you for your project description. It is on the BCN website 
now.
best wishes,
Diana


Dear Ms. Diana Koopmans,

I send you the general description of my research project.

I hope that you will encounter no difficulty in putting this
information on the BCN website.
Otherwise do not hesitate to contact me again.

Best wishes,

	Marius Bulacu
-------------------------------------------------------

Bulacu M.L. (Marius)
E-mail : m.bulacu@ai.rug.nl

Artificial Intelligence Institute
University of Groningen
Grote Kruisstraat 2/1
9712 TS Groningen
The Netherlands

Telephone number:
+31 50 363 6399

Supervisors:
Prof. Dr. L.R.B. Schomaker

Period of employment:
01-03-2002 - 01-03-2006

Financed by:
University of Groningen


Active Vision in Reading Systems:
Exploiting the notion of selective attentionin the machine recognition of script

A basic difference between human reading and machine reading is the use of memory.
Whereas algorithms for machine reading usually store complete scanned images and
start subsequent segmentation and further processing, the human reader uses
selective attention to drive the physical scanning process.
Short eye fixations are alternated by brief movements, saccades, to the next
prospect region from which to extract information which is estimated to help
in the deciphering process. This means that the use of high-level information
is not at all delegated to a 'late' or 'high' level of processing. On the contrary,
lexical, syntactic, semantic and pragmatic information play an essential role in
the physical scanning process itself. It is believed that the processing time which
is saved by this economical and evolutionarily endorsed architecture can be used to
improve the recognition performances, also in machine recognition architectures.

It should be noted that, although processor speeds have increased thirtyfold over
the last decade, the error rates in handwriting recognition and in computer vision
are decreasing at a much slower pace. Therefore it is estimated that the development
of new architectures for visual processing may contribute substantially to allow for
real-time intelligent vision in future autonomous systems.

The goal of this project is to develop a perceptual/cognitive architecture for reading.
In order to expose the fundamental differences between active vision and brute-force
image processing, an experimental paradigm will be developed using a controllable
camera (attitude, zoom, focus) with a view field which is coarsely modeled after
the human eye (foveal acuity, reduced parafoveal acuity but improved temporal
sensitivity). Based on human eye-movement data in reading, the system is trained
to spot text patterns in its environment and to decipher the image content by:
	- controlled movement
	- central integrative coding.

In the first stage of research, the model will be tested in a static setup,
the controllable camera is attached to a rigid wall. In the second stage of
the project, the active-vision reader will be used to control the navigation
of an autonomous robot system on the basis of text tags in its environment.

Recurring research themes:
	- the relation between natural and artificial systems
	- statistical vs knowledge-based methodology
	- computational complexity and cognitive-resource management.
Diana Koopmans
AIO-Coordinator BCN


